Fix inconsistencies in e and its documentation

diff --git a/bin/e b/bin/e
--- a/bin/e
+++ b/bin/e
@@ -4,7 +4,7 @@
 # Purpose   : Start Emacs in terminal mode.  Support multiple environments
 # Created   : Wednesday, May 22 2024.
 # Author    : Pierre Rouleau <prouleau001@gmail.com>
-# Time-stamp: <2026-10-07 23:16:54 EDT, updated by Pierre Rouleau>
+# Time-stamp: <2026-10-08 08:33:41 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 # Module Description
 # ------------------
@@ -53,7 +53,7 @@ print_usage()
   • Execute emacs -nw with the specified OPTION-or-FILENAME.
     This does not auto-load any session.
 
- Usage: %s [-s] [SESSION-NAME] [--] [OPTION-or-FILENAME]...
+ Usage: %s -s [SESSION-NAME] [--] [OPTION-or-FILENAME]...
         %s --session=SESSION_NAME [OPTION-or-FILENAME]...
         PEL_SESSION=SESSION-NAME %s -s [OPTION-or-FILENAME]...
 
@@ -77,10 +77,11 @@ print_usage()
       is auto-loaded.  The, special name '.' (without quotes) identifies a
       directory-specific session name extracted from the PEL easysession
       catalog.
-    • Any word (except '--') directly following '-s', '--session=' or the
+    • The name directly following '-s', '--session=' or the
       'PEL_SESSION=' identifies the session name and overrides the
       session name that could be identified by the current value of
-      the PEL_SESSION environment variable.
+      the PEL_SESSION environment variable.  This word cannot be '--'.
+
 
   The -s and --session options force the automatic loading of a session
   using the Emacs easysession logic and are active when the following
@@ -90,22 +91,27 @@ print_usage()
     • The easysession.el package is installed (PEL installs it when
       Emacs starts and pel-use-easysession is on)
     • The session directory exists (see FILES).
+  For unnamed, directory-specific session invoked with -s without a name,
+  the following extra condition are checked:
     • The PEL easysession catalog file exists (see FILES).
-      • It has a line that identifies a session for the current directory.
-      • That file is present in the session directory.
+    • It has a line that identifies a session for the current directory.
+    • That file is present in the session directory.
 
  FILES
    • Emacs user directory: most often: '~/.emacs.d' but also '~/.config/emacs/'
                            on some XDG compliant systems.
    • session directory: the 'easysession' sub-directory of the Emacs user
                         directory.
-   • PEL easysession catalog file:  'pel-easysession-catalog.txt;' inside the
+   • PEL easysession catalog file:  'pel-easysession-catalog.txt' inside the
                                      Emacs user directory.
 
  ENVIRONMENT
-    • PEL_SESSION_CATALOG : the file name (with absolute path) of the
-                            PEL easysession catalog file, overriding the
-                            default described above.
+    • PEL_SESSION_CATALOG : the file name of the PEL easysession catalog file.
+                            No path; the file is located inside the user's
+                            Emacs directory. Overrides the default shown
+                            above.  Required when the user changed the default
+                            value of PEL pel-easysession-catalog-filename
+                            user-option in Emacs.
 
  NOTES
     • %s starts Emacs within the current shell; Emacs gets access to the
@@ -115,18 +121,31 @@ print_usage()
       processes from different shells, each ones having different specialized
       environments, and potentially an associated session.
 
+ LIMITATIONS
+    • The -s option does not check if a session for the current working
+      directory exists in the PEL easysession catalog file.  That is done
+      by Emacs pel-session.el logic.  No harm is done: Emacs won't auto-load
+      a session.  Use it as a reminder to save the session with a name
+      associated with the current working directory.
+    • When auto-loading a session with easysession, %s assumes that the
+      session information was stored inside files located inside the same
+      Emacs user directory Emacs will use now.  It does not support
+      restoration of sessions created by invoking Emacs with its
+      --init-directory option.
+
  DIAGNOSTICS
-  %s is silent by default.  To force it to display error messages that describe
-  unmet conditions for the -s option, set the PEL_DIAG environment variable to
-  1.  If there is a problem, it will be displayed and the script will exit
-  before invoking Emacs.  Use that to troubleshoot environment problems.
+  %s print error information on failures. It prints extra details when the
+  PEL_DIAG environment variable is set to 1.  Specifically it displays more
+  information when conditions are not met for the loading of a session.
+  Use that to troubleshoot environment problems.
   • With USRHOME installed, type: setenv PEL_DIAG 1
 
  EXIT CODE
-  • 3 : emacs invoked inside emacs, prompt read failed.
-  • 2 : emacs not found in PATH
-  • 1 : command line error
-  • 0 : success
+  • 0 : success,
+  • 1 : command line error,
+  • 2 : emacs not found in PATH,
+  • 3 : emacs invoked inside emacs, prompt read failed,
+  • 4 : fail to identify emacs users' directory for session load operation.
 
  SEE ALSO
   • ge : to start a Graphics-based Emacs process.
@@ -138,7 +157,7 @@ print_usage()
     • easysession.el Emacs package documentation.
 
 " "$pgm_name" "$pgm_name" "$pgm_name" "$pgm_name" "$pgm_name" "$pgm_name" \
-  "$pgm_name" "$pgm_name" "$pgm_name"
+  "$pgm_name" "$pgm_name" "$pgm_name" "$pgm_name"
 }
 
 # --
@@ -156,19 +175,6 @@ fi
 if ! command -v emacs > /dev/null 2>&1; then
     printf -- "ERROR: emacs is not found in PATH!\n" >&2
     exit 2
-fi
-
-# --
-# Identify location of important directory and files.
-# Uses emacs (now that we know that it is accessible).
-
-EMACS_DIR=$(emacs -Q --batch --eval="(princ (expand-file-name (directory-file-name user-emacs-directory)))")
-EASYSESSION_SESSION_DIR="$EMACS_DIR/easysession"
-if [ -n "$PEL_SESSION_CATALOG" ]; then
-    EASYSESSION_SESSION_CATALOG="$EMACS_DIR/$PEL_SESSION_CATALOG"
-else
-    # Use the default
-    EASYSESSION_SESSION_CATALOG="$EMACS_DIR/pel-easysession-catalog.txt"
 fi
 
 # ----------------------------------------------------------------------------
@@ -201,9 +207,9 @@ session_name=
 
 # Loop through arguments to look for -s at the very beginning.
 # Extract the session name; support the following possibilities:
-#  -s              -> session_name = "."
-#  -s ABC          -> session_name = "ABC"
-#  --session=ABC   -> session_name = "ABC"
+#  -s            -> session_name = $PEL_SESSION value, "." if it does not exist
+#  -s ABC        -> session_name = "ABC"
+#  --session=ABC -> session_name = "ABC"
 while [ $# -gt 0 ]; do
     case "$1" in
         -s)
@@ -261,6 +267,22 @@ fi
 dir_has_file=0
 
 if [ "$with_s_flag" -eq 1 ]; then
+    # User wants to auto-load an easysession session.
+    # Identify location of important directory and files required for this.
+    # Uses emacs (we know that it is accessible).
+    if EMACS_DIR=$(emacs -Q --batch --eval="(princ (expand-file-name (directory-file-name user-emacs-directory)))") 2>/dev/null; then
+        EASYSESSION_SESSION_DIR="$EMACS_DIR/easysession"
+        if [ -n "$PEL_SESSION_CATALOG" ]; then
+            EASYSESSION_SESSION_CATALOG="$EMACS_DIR/$PEL_SESSION_CATALOG"
+        else
+            # Use the default
+            EASYSESSION_SESSION_CATALOG="$EMACS_DIR/pel-easysession-catalog.txt"
+        fi
+    else
+        printf -- "ERROR: cannot identify Emacs user directory. Exiting.\n"
+        exit 4
+    fi
+
     if [ -d "$EASYSESSION_SESSION_DIR" ]; then
         # The directory exists.  Check if it holds any file.
         # The pattern inside quotes ensures we check the literal folder,
