Fix: on macOS, ec now able to distinguish default socket.
Also reject invalid --start-daemon option that specifies a name.
Ideally the syntax would support it, but code is currently not geared for it;
the --name option is required.

diff --git a/bin/ec b/bin/ec
--- a/bin/ec
+++ b/bin/ec
@@ -4,7 +4,7 @@
 # Purpose   : Launch an Emacs client to an Emacs Daemon - start the deamon if necessary.
 # Created   : Wednesday, May 22 2024.
 # Author    : Pierre Rouleau <prouleau001@gmail.com>
-# Time-stamp: <2024-05-24 12:11:41 EDT, updated by Pierre Rouleau>
+# Time-stamp: <2024-05-24 14:16:43 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 # Description
 # -----------
@@ -57,11 +57,6 @@ ec : Open specified files in emacsclient. Start Emacs daemon if necessary.
  Note: under macOS, to be able to launch an Emacs client that is a GUI Emacs
        the GUI supporting Emacs from https://emacsformacosx.com/
        must be installed.
-
- BUG: Under macOS, ec can't distinguish Emacs daemon using the default server
-      if a deamon with a named socket is used.  To work around this, always
-      start an Emacs daemon with the default socket first if you plan to also
-      use an Emacs daemon with a named socket.
 "
     fi
 }
@@ -88,6 +83,16 @@ if [ "$1" = "--start-daemon" ] ; then
     start_client=false
     shift
 fi
+# Ensure that that --start-daemon option does not have extra text to it.
+# ie: reject something like --start-daemon=NAME
+case "$1" in
+    --start-daemon=*)
+        echo "*** ec: ERROR ***"
+        echo "    Invalid option: $1"
+        echo "*****************"
+        print_usage
+        exit 1
+esac
 
 # ----------------------------------------------------------------------------
 # Check if the deamon/client use the default or specified socket filename
@@ -119,10 +124,10 @@ case "${os_name}" in
             exit 1
         fi
 
-        # On macOS, start the graphical Emacs daemon if it is not already running.
+        # On macOS, start the graphics-capable Emacs daemon if it is not already running.
         if [ -z "${daemon_name}" ]; then
             # shellcheck disable=SC2009
-            if ps -ax | grep Emacs.app | grep -v grep | grep -- "--bg-daemon=" > /dev/null; then
+            if ps -ax | grep Emacs.app | grep -v grep | grep -- "--bg-daemon=\\\0123,4\\\012$" > /dev/null; then
                 if [ "${start_client}" = "false" ]; then
                     echo "ec: Emacs daemon (for default socket name) is already running!"
                     exit 1
