Improved etags-lisp and etags-make: no arg is now supported, follow symlinks
- Eliminate code duplication via functions.
- Support multiple directories properly.
- Support no argument to search in current directory tree.
- Supports symlinks for files and directories.
- Sort generated list file regardless of the tool used to generate it.
- Only print name of found files on stdout, all extra messages ate printed on stderr.

diff --git a/bin/etags-lisp b/bin/etags-lisp
--- a/bin/etags-lisp
+++ b/bin/etags-lisp
@@ -4,7 +4,7 @@
 #  Purpose   : Build Emacs Tags file for Lisp source code files.
 #  Created   : Tuesday, November 10 2020.
 #  Author    : Pierre Rouleau <prouleau001@gmail.com>
-#  Time-stamp: <2025-01-16 17:13:38 EST, updated by Pierre Rouleau>
+#  Time-stamp: <2025-04-24 23:37:19 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 #  Module Description
 #  ------------------
@@ -13,10 +13,6 @@
 # sub-directory tree(s) specified in the command line.
 # This includes the files with the following file extensions:
 # .cl, .clisp, .l, .lisp, .LSP, .lsp and .ml.
-#
-# Usage:
-#  - cd where you want to store the TAGS file
-#  - etags-lisp DIRPATH [DIRPATH ...]
 #
 
 # ----------------------------------------------------------------------------
@@ -33,52 +29,56 @@
 #
 # - To force use of find, set the ETAGS_USE_FIND environment variable to 1.
 
-# TODO: eliminate code duplication while keeping capability to stay
-#       compatible with various shells (sh, bash, etc...)
-
 # ----------------------------------------------------------------------------
 #  Code
 #  ----
 
+pgm_name="$(basename "$0")"
 
 print_usage()
 {
     printf -- "
-etags-lisp: build an etags-compliant TAGS in the current directory
-            for all Lisp and C source code files in the specified
+%s: build an etags-compliant TAGS in the current directory
+            for all Common Lisp source code files in the specified
             directory trees(s).
 
-  Usage: etags-lisp -h|--help
+ Usage: %s -h|--help
 
-   • Print this help information.
+  • Print this help information.
 
-  Usage: etags-lisp DIRPATH [DIRPATH ...]
+ Usage: %s [DIRPATH ...]
 
-   • [Re]build an etags-compliant TAGS file in current directory
-     for the Common Lisp files in the directory tree(s) identified
-     on the command line.
-   • Overwrites any TAGS file in the current directory.
-   • Inspects content of .cl, .clisp, .l, .lisp, .LSP, .lsp and .ml
-     and their gz compressed files.
-   • Stores the names of inspected files in the file named
-    .etags-lisp-files.txt stored in the same directory as TAGS.
-   • Uses etags to build the TAGS file by default.
-     ETAGS_USE_UCTAGS is ignored because Ctags does not handle .gz files.
-   • Uses fast 'fdfind' or 'fd' if available, 'find' otherwise.
-     - The 'fd' utility is from: https://github.com/sharkdp/fd
-     - In some Linux distros, 'fd' is renamed 'fdfind'.
-   • To force the use of 'find', set ETAGS_USE_FIND environment
-     variable to 1.
-   • ☝️  When 'fdfind' or 'fd' is used, the content of files identified
-     by the .gitignore, .ignore or .fdignore files are ignored.
-   • Prints the path of the find program used and when
-     repository ignore files are scanned.
-"
+  • [Re]build an etags-compliant TAGS file in current directory
+    for the Common Lisp files found:
+    - in the DIRPATH directory tree(s) identified on the command line, or
+      the current directory if none is specified.
+  • Follows symbolic links both for directories and files.
+  • Overwrites any TAGS file in the current directory.
+  • Inspects content of .cl, .clisp, .l, .lisp, .LSP, .lsp and .ml
+    and their gz compressed files.
+  • Stores the names of inspected files in the file named
+   .etags-lisp-files.txt stored in the same directory as TAGS.
+  • Uses etags to build the TAGS file by default.
+    ETAGS_USE_UCTAGS is ignored because Ctags does not handle .gz files.
+  • Uses fast 'fdfind' or 'fd' if available, 'find' otherwise.
+    - The 'fd' utility is from: https://github.com/sharkdp/fd
+    - In some Linux distros, 'fd' is renamed 'fdfind'.
+  • To force the use of 'find', set ETAGS_USE_FIND environment
+    variable to 1.
+  • ☝️  When 'fdfind' or 'fd' is used, the content of files identified
+    by the .gitignore, .ignore or .fdignore files are ignored.
+  • Info printed on stderr:
+    • The path of the find program used and when repository ignore files
+      are skipped from the scan.
+    • A count of found files, and the name of the file that holds them.
+  • The only output on stdout is the list of files found.
+    This allows this script to be used as the first in a pipe
+    to do other processing with the list of files found.
+" "$pgm_name" "$pgm_name" "$pgm_name"
     if [ "$ETAGS_USE_FIND" = "1" ]; then
         printf -- "
-⚠️   ETAGS_USE_FIND is set to 1, forcing the use of 'find'!
-    • To prevent this, set it to 0 or remove that
-      environment variable.
+⚠️   ETAGS_USE_FIND is currently set to 1, forcing the use of 'find'!
+    • To prevent this, set it to 0 or remove that environment variable.
     • With USRHOME, you can use setenv and clrenv.
       See: https://github.com/pierre-rouleau/usrhome
 "
@@ -93,17 +93,14 @@ run__etags_lisp()
 
     etags -
     if [ "$ETAGS_USE_UCTAGS" = "1" ]; then
-        printf -- "-> Using etags despite ETAGS_USE_CTAGS since ctags can't handle compressed file\n"
+        printf -- "-> Using etags despite ETAGS_USE_CTAGS since ctags can't handle compressed file\n"  1>&2
     fi
 }
 
 # --
 # Check validity of arguments
 
-if [ -z "$1" ]; then
-    print_usage
-    exit 1
-elif [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
     print_usage
     if [ "$#" = "1" ]; then
         exit 0
@@ -121,89 +118,143 @@ fi
 dpaths=
 for dname in "$@"; do
     if [ ! -d "${dname}" ]; then
-        printf -- "Specified directory does not exists: %s\n" "${dname}"
+        printf -- "Specified directory does not exists: %s\n" "${dname}" 1>&2
         exit 2
     fi
     dpath="$(realpath "${dname}")"
     for dp in ${dpaths}; do
         if [ "$dp" = "$dpath" ]; then
-            printf -- "Multiple entry of directory: %s\n" "${dname}"
+            printf -- "Multiple entry of directory: %s\n" "${dname}" 1>&2
             exit 3
         fi
         # check if new entry is a sub-directory of an exiting entry
         case "${dpath}" in
             "${dp}/"*)
-                printf -- "%s is a sub-dir of already specified %s\n" "${dname}" "${dp}"
+                printf -- "%s is a sub-dir of already specified %s\n" "${dname}" "${dp}" 1>&2
                 exit 3
                 ;;
         esac
         # check if new entry is a parent directory of an existing entry
         case "${dp}" in
             "${dpath}/"*)
-                printf -- "%s is a parent dir of already specified %s\n" "${dname}" "${dp}"
+                printf -- "%s is a parent dir of already specified %s\n" "${dname}" "${dp}" 1>&2
                 exit 3
                 ;;
         esac
-
     done
     dpaths="${dpaths} ${dpath}"
 done
 
 # --
 
-# Find the files, pass their names to etags which creates the TAGS file.
-# To find the files, try to use fd or fdfind if they exist,
-# otherwise use find.  Echo the actual program used to find files.
-if [ "$ETAGS_USE_FIND" = "1" ]; then
-    echo "- ETAGS_USE_FIND forces the use of find!"
-    echo "-> Using" "$(which find)"
-    find -f "$@" \( -name "*.cl"    -or -name "*.cl.gz" \
+# Define a function that searches into 1 directory
+# and accumulates the list of found files into the
+# file '.etags-lisp-files.txt'.
+
+search_with_find()
+{
+    # Arg: dirname : name of directory tree to search
+
+    find -L -f "$dirname" \( -name "*.cl"    -or -name "*.cl.gz" \
          -or -name "*.clisp" -or -name "*.clisp.gz" \
          -or -name "*.l"     -or -name "*.l.gz"    \
          -or -name "*.lisp"  -or -name "*.lisp.gz" \
          -or -name "*.LSP"   -or -name "*.LSP.gz" \
          -or -name "*.lsp"   -or -name "*.lsp.gz" \
          -or -name "*.ml"    -or -name "*.ml.gz" \
-         \)  -print | tee .etags-lisp-files.txt | run__etags_lisp
+         \)  -print | tee -a .etags-lisp-files.txt
+}
+
+search_with_fd()
+{
+    # Arg: dirname : name of directory tree to search
+    # Arg: fd_pgm  : fd or fdfind
+
+    ${fd_pgm} -L --type f \
+              -e .cl    -e .cl.gz \
+              -e .clisp -e .clisp.gz \
+              -e .l     -e .l.gz \
+              -e .lisp  -e .lisp.gz \
+              -e .LSP   -e .LSP.gz \
+              -e .lsp   -e .lsp.gz \
+              -e .ml    -e .ml.gz \
+              "$dirname" | tee -a .etags-lisp-files.txt
+}
+
+search()
+{
+    # Arg: dirname : name of directory tree to search
+    # Arg: search_with : find or fd
+    case "$search_with" in
+        find)
+            search_with_find
+            ;;
+
+        fd)
+            search_with_fd
+            ;;
+    esac
+}
+
+# --
+# First prepare environment
+# Select the method to search for files.
+# - Try to use fd or fdfind if they exist,
+#   otherwise use find.
+# - Echo the actual program used to find files (on stderr).
+if [ "$ETAGS_USE_FIND" = "1" ]; then
+    search_with='find'
+    echo "- ETAGS_USE_FIND forces the use of find!" 1>&2
+    echo "-> Using" "$(which find)"                 1>&2
 else
     if [ -x "$(command -v fdfind)" ]; then
-        echo "-> Using" "$(which fdfind)"
-        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore"
-        fdfind --type f \
-               -e .cl    -e .cl.gz \
-               -e .clisp -e .clisp.gz \
-               -e .l     -e .l.gz \
-               -e .lisp  -e .lisp.gz \
-               -e .LSP   -e .LSP.gz \
-               -e .lsp   -e .lsp.gz \
-               -e .ml    -e .ml.gz \
-               "$@" | tee .etags-lisp-files.txt | run__etags_lisp
+        search_with='fd'
+        fd_pgm=fdfind
+        echo "-> Using" "$(which fdfind)"  1>&2
+        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
+
     elif [ -x "$(command -v fd)" ]; then
-        echo "-> Using" "$(which fd)"
-        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore"
-        fd --type f \
-           -e .cl    -e .cl.gz \
-           -e .clisp -e .clisp.gz \
-           -e .l     -e .l.gz \
-           -e .lisp  -e .lisp.gz \
-           -e .LSP   -e .LSP.gz \
-           -e .lsp   -e .lsp.gz \
-           -e .ml    -e .ml.gz \
-           "$@" | tee .etags-lisp-files.txt | run__etags_lisp
+        search_with='fd'
+        fd_pgm=fd
+        echo "-> Using" "$(which fd)" 1>&2
+        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
     else
-        echo "-> Using" "$(which find)"
-        find -f "$@" \(   -name "*.cl"    -or -name "*.cl.gz" \
-             -or -name "*.clisp" -or -name "*.clisp.gz" \
-             -or -name "*.l"     -or -name "*.l.gz"    \
-             -or -name "*.lisp"  -or -name "*.lisp.gz" \
-             -or -name "*.LSP"   -or -name "*.LSP.gz" \
-             -or -name "*.lsp"   -or -name "*.lsp.gz" \
-             -or -name "*.ml"    -or -name "*.ml.gz" \
-             \)  -print | tee .etags-lisp-files.txt | run__etags_lisp
+        search_with='find'
+        echo "-> Using" "$(which find)" 1>&2
     fi
 fi
+
+# -- proceed
+# remove the old list of files.
+rm -f .etags-lisp-files.txt
+
+# Search in all specified directory to build the list of
+# files in the file '.etags-lisp-files.txt'.
+
+printf -- "%s - Processing %s/ ...\n" "${pgm_name}" "$(pwd)" 1>&2
+
+if [ -z "$1" ]; then
+    dirname="."
+    search
+else
+    for dirname in "$@"; do
+        search
+    done
+fi
+
+
+# Then run etags on these files, and sort them in the etags file
+sort < .etags-lisp-files.txt | uniq >  .etags-lisp-files.1.txt
+rm -f .etags-lisp-files.txt
+mv .etags-lisp-files.1.txt .etags-lisp-files.txt
+run__etags_lisp < .etags-lisp-files.txt
+
 file_count="$(wc -l .etags-lisp-files.txt | awk '{print $1}')"
-printf "%s files found and processed. List stored in: .etags-lisp-files.txt\n" "${file_count}"
+printf "\
+%s - %s files found and processed.
+           Created: %s/TAGS
+           Scanned file list stored in: %s/.etags-lisp-files.txt
+" "${pgm_name}" "${file_count}" "$(pwd)" "$(pwd)" 1>&2
 
 # -----------------------------------------------------------------------------
 # Local Variables:
diff --git a/bin/etags-make b/bin/etags-make
--- a/bin/etags-make
+++ b/bin/etags-make
@@ -4,7 +4,7 @@
 #  Purpose   : Build Emacs Tags file for Make source code files.
 #  Created   : Thursday, June 6, 2024
 #  Author    : Pierre Rouleau <prouleau001@gmail.com>
-#  Time-stamp: <2025-01-16 17:11:57 EST, updated by Pierre Rouleau>
+#  Time-stamp: <2025-04-24 23:42:07 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 #  Module Description
 #  ------------------
@@ -12,11 +12,6 @@
 # Build an Emacs Tags file for all Make source code files in the
 # sub-directory tree.  This includes the Makefile, makefile, GNUMakefile,
 # Makefile.in and makefile.am files and all .mk and .mak files.
-#
-#
-# Usage:
-#  - cd where you want to store the TAGS file
-#  - etags-make DIRPATH [DIRPATH ...]
 #
 
 # ----------------------------------------------------------------------------
@@ -40,55 +35,56 @@
 #   You can also set ETAGS_USE_UCTAGS to the absolute path of the
 #   Universal Ctags executable file.
 
-# TODO: eliminate code duplication while keeping capability to stay
-#       compatible with various shells (sh, bash, etc...)
-
 # ----------------------------------------------------------------------------
 #  Code
 #  ----
 
+pgm_name="$(basename "$0")"
+
 print_usage()
 {
     printf -- "
-etags-make: build an etags-compliant TAGS in the current directory
+%s: build an etags-compliant TAGS in the current directory
           for all GNU Make source code files in the specified
           directory tree(s).
 
- Usage: etags-make -h|--help
+ Usage: %s -h|--help
 
-   • Print this help information.
+  • Print this help information.
 
-  Usage: etags-make [-u] DIRPATH [DIRPATH ...]
+ Usage: %s [-u] [DIRPATH ...]
 
-   • [Re]build an etags-compliant TAGS file in current directory
-     for the GNU Make source code files in the directory
-     tree(s) identified on the command line.
-   • Uses etags to build the TAGS file by default, but
-     -u : force use Universal Ctags (ctags) instead of etags.
-   • Set ETAGS_USE_UCTAGS to 1 or the absolute path of
-     Universal Ctags executable file to force using Universal Ctags.
-     When setting it to 1, the ctags found in PATH is expected
-     to be Universal Ctags.
-   • Overwrites any TAGS file in the current directory.
-   • Inspects content of the Makefile, makefile, GNUMakefile,
-      Makefile.in, makefile.am and all .mk and .mak files.
-   • Stores the names of inspected files in the file named
-     .etags-make-files.txt in the current directory.
-   • Uses fast 'fdfind' or 'fd' if available, 'find' otherwise.
-     - The 'fd' utility is from: https://github.com/sharkdp/fd
-     - In some Linux distros, 'fd' is renamed 'fdfind'.
-   • To force the use of 'find', set ETAGS_USE_FIND environment
-     variable to 1.
-   • ☝️  When 'fdfind' or 'fd' is used, the content of files identified
-     by the .gitignore, .ignore or .fdignore files are ignored.
-   • Prints the path of the find program used and when
-     repository ignore files are scanned.
-"
+  • [Re]build an etags-compliant TAGS file in current directory
+    for the GNU Make source code files found:
+    - in the DIRPATH directory tree(s) identified on the command line, or
+      the current directory if none is specified.
+  • Follows symbolic links both for directories and files.
+  • Uses etags to build the TAGS file by default, but
+    -u : force use Universal Ctags (ctags) instead of etags.
+  • Set ETAGS_USE_UCTAGS to 1 or the absolute path of
+    Universal Ctags executable file to force using Universal Ctags.
+    When setting it to 1, the ctags found in PATH is expected
+    to be Universal Ctags.
+  • Overwrites any TAGS file in the current directory.
+  • Inspects content of the Makefile, makefile, GNUMakefile,
+     Makefile.in, makefile.am and all .mk and .mak files.
+  • Stores the names of inspected files in the file named
+    .etags-make-files.txt in the current directory.
+  • Uses fast 'fdfind' or 'fd' if available, 'find' otherwise.
+    - The 'fd' utility is from: https://github.com/sharkdp/fd
+    - In some Linux distros, 'fd' is renamed 'fdfind'.
+  • To force the use of 'find', set ETAGS_USE_FIND environment
+    variable to 1.
+  • ☝️  When 'fdfind' or 'fd' is used, the content of files identified
+    by the .gitignore, .ignore or .fdignore files are ignored.
+  • The only output on stdout is the list of files found.
+    This allows this script to be used as the first in a pipe
+    to do other processing with the list of files found.
+" "$pgm_name" "$pgm_name" "$pgm_name"
     if [ "$ETAGS_USE_FIND" = "1" ]; then
         printf -- "
-⚠️   ETAGS_USE_FIND is set to 1, forcing the use of 'find'!
-    • To prevent this, set it to 0 or remove that
-      environment variable.
+⚠️   ETAGS_USE_FIND is currently set to 1, forcing the use of 'find'!
+    • To prevent this, set it to 0 or remove that environment variable.
     • With USRHOME, you can use setenv and clrenv.
       See: https://github.com/pierre-rouleau/usrhome
 "
@@ -104,14 +100,14 @@ run__etags__make()
     if [ -n "$ETAGS_USE_UCTAGS" ]; then
         if [ "$ETAGS_USE_UCTAGS" = "1" ]; then
             xargs ctags --output-format=etags
-            printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n"  "$(which ctags)"
+            printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n"  "$(which ctags)" 1>&2
         elif [ -x "$ETAGS_USE_UCTAGS" ]; then
             xargs "$ETAGS_USE_UCTAGS" --output-format=etags
-            printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n"  "$ETAGS_USE_UCTAGS"
+            printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n"  "$ETAGS_USE_UCTAGS" 1>&2
         else
-            printf -- "*** etags-make ERROR: invalid ETAGS_USE_UCTAGS value\n"
-            printf -- "***  ETAGS_USE_UCTAGS : %s\n" "$ETAGS_USE_UCTAGS"
-            printf -- "***  This is not 1 nor a valid executable file name.\n"
+            printf -- "*** ERROR: %s : invalid ETAGS_USE_UCTAGS value\n" "${pgm_name}" 1>&2
+            printf -- "***  ETAGS_USE_UCTAGS : %s\n" "$ETAGS_USE_UCTAGS" 1>&2
+            printf -- "***  This is not 1 nor a valid executable file name.\n" 1>&2
             exit 4
         fi
     else
@@ -119,36 +115,10 @@ run__etags__make()
     fi
 }
 
-run__append_etags()
-{
-    # Expects no argument, but expects a list of files to parse on stdin.
-
-    if [ -n "$ETAGS_USE_UCTAGS" ]; then
-        if [ "$ETAGS_USE_UCTAGS" = "1" ]; then
-            xargs ctags --append --output-format=etags
-            printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n"  "$(which ctags)"
-        elif [ -x "$ETAGS_USE_UCTAGS" ]; then
-            xargs "$ETAGS_USE_UCTAGS" --output-format=etags
-            printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n"  "$ETAGS_USE_UCTAGS"
-        else
-            printf -- "*** etags-make ERROR: invalid ETAGS_USE_UCTAGS value\n"
-            printf -- "***  ETAGS_USE_UCTAGS : %s\n" "$ETAGS_USE_UCTAGS"
-            printf -- "***  This is not 1 nor a valid executable file name.\n"
-            exit 4
-        fi
-    else
-        etags --append -
-    fi
-}
-
-
 # --
 # Check validity of arguments
 
-if [ -z "$1" ]; then
-    print_usage
-    exit 1
-elif [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
     print_usage
     if [ "$#" = "1" ]; then
         exit 0
@@ -157,15 +127,13 @@ elif [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
     fi
 fi
 
-# --
-
 if [ "$1" = "-u" ]; then
     if [ -z "$ETAGS_USE_UCTAGS" ]; then
-        echo "etags-make: -u option requests use of Universal Ctags."
+        echo "%s: -u option requests use of Universal Ctags." "${pgm_name}" 1>&2
         ETAGS_USE_UCTAGS=1
     else
-        echo "etags-make: -u option not necessary (but does no harm)."
-        echo " ETAGS_USE_UCTAGS is already set to: $ETAGS_USE_UCTAGS"
+        echo "%s: -u option not necessary (but does no harm)." "${pgm_name}" 1>&2
+        echo " ETAGS_USE_UCTAGS is already set to: $ETAGS_USE_UCTAGS"  1>&2
     fi
     shift
 fi
@@ -179,42 +147,44 @@ fi
 dpaths=
 for dname in "$@"; do
     if [ ! -d "${dname}" ]; then
-        printf -- "Specified directory does not exists: %s\n" "${dname}"
+        printf -- "Specified directory does not exists: %s\n" "${dname}" 1>&2
         exit 2
     fi
     dpath="$(realpath "${dname}")"
     for dp in ${dpaths}; do
         if [ "$dp" = "$dpath" ]; then
-            printf -- "Multiple entry of directory: %s\n" "${dname}"
+            printf -- "Multiple entry of directory: %s\n" "${dname}" 1>&2
             exit 3
         fi
         # check if new entry is a sub-directory of an exiting entry
         case "${dpath}" in
             "${dp}/"*)
-                printf -- "%s is a sub-dir of already specified %s\n" "${dname}" "${dp}"
+                printf -- "%s is a sub-dir of already specified %s\n" "${dname}" "${dp}" 1>&2
                 exit 3
                 ;;
         esac
         # check if new entry is a parent directory of an existing entry
         case "${dp}" in
             "${dpath}/"*)
-                printf -- "%s is a parent dir of already specified %s\n" "${dname}" "${dp}"
+                printf -- "%s is a parent dir of already specified %s\n" "${dname}" "${dp}" 1>&2
                 exit 3
                 ;;
         esac
-
     done
     dpaths="${dpaths} ${dpath}"
 done
 
+# --
 
-# Find the files, pass their names to etags which creates the TAGS file.
-# To find the files, try to use fd or fdfind if they exist,
-# otherwise use find.  Echo the actual program used to find files.
-if [ "$ETAGS_USE_FIND" = "1" ]; then
-    echo "- ETAGS_USE_FIND forces the use of find!"
-    echo "-> Using" "$(which find)"
-    find -f "$@" \( \
+# Define a function that searches into 1 directory
+# and accumulates the list of found files into the
+# file '.etags-make-files.txt'.
+
+search_with_find()
+{
+    # Arg: dirname : name of directory tree to search
+
+    find -L -f "$dirname" \( \
          -name     "Makefile" \
          -or -name "makefile" \
          -or -name "GNUMakefile" \
@@ -222,39 +192,95 @@ if [ "$ETAGS_USE_FIND" = "1" ]; then
          -or -name "Makefile.am" \
          -or -name "*\.mk" \
          -or -name "*\.mak" \
-         \)  -print | tee .etags-make-files.txt | run__etags__make
+         \)  -print | tee -a .etags-make-files.txt
+}
+
+search_with_fd()
+{
+    # Arg: dirname : name of directory tree to search
+    # Arg: fd_pgm  : fd or fdfind
+
+    ${fd_pgm} -L --type f '((makefile)|((GNU)?Makefile(.((in)|(am)))?))$' \
+           "$dirname" | tee -a .etags-make-files.txt
+    # Then the .mk and .mak make files
+    ${fd_pgm} -L --type f -e .mk -e .mak\
+           "$dirname" | tee -a .etags-make-files.txt
+}
+
+search()
+{
+    # Arg: dirname : name of directory tree to search
+    # Arg: search_with : find or fd
+    case "$search_with" in
+        find)
+            search_with_find
+            ;;
+
+        fd)
+            search_with_fd
+            ;;
+    esac
+}
+
+# --
+# First prepare environment
+# Select the method to search for files.
+# - Try to use fd or fdfind if they exist,
+#   otherwise use find.
+# - Echo the actual program used to find files (on stderr).
+if [ "$ETAGS_USE_FIND" = "1" ]; then
+    search_with='find'
+    echo "- ETAGS_USE_FIND forces the use of find!" 1>&2
+    echo "-> Using" "$(which find)"                 1>&2
 else
     if [ -x "$(command -v fdfind)" ]; then
-        echo "-> Using" "$(which fdfind)"
-        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore"
-        fdfind --type f '((makefile)|((GNU)?Makefile(.((in)|(am)))?))$' \
-               "$@" | tee .etags-make-files.txt | run__etags__make
-        # Then the .mk and .mak make files
-        fdfind --type f -e .mk -e .mak\
-               "$@" | tee -a .etags-make-files.txt | run__append_etags
+        search_with='fd'
+        fd_pgm=fdfind
+        echo "-> Using" "$(which fdfind)"  1>&2
+        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
+
     elif [ -x "$(command -v fd)" ]; then
-        echo "-> Using" "$(which fd)"
-        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore"
-        fd --type f '((makefile)|((GNU)?Makefile(.((in)|(am)))?))$' \
-           "$@" | tee .etags-make-files.txt | run__etags__make
-        # Then the .mk and .mak make files
-        fd --type f -e .mk -e .mak\
-           "$@" | tee -a .etags-make-files.txt | run__append_etags
+        search_with='fd'
+        fd_pgm=fd
+        echo "-> Using" "$(which fd)" 1>&2
+        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
     else
-        echo "-> Using" "$(which find)"
-        find -f "$@" \( \
-             -name     "Makefile" \
-             -or -name "makefile" \
-             -or -name "GNUMakefile" \
-             -or -name "Makefile.in" \
-             -or -name "Makefile.am" \
-             -or -name "*\.mk" \
-             -or -name "*\.mak" \
-             \) -print | tee .etags-make-files.txt | run__etags__make
+        search_with='find'
+        echo "-> Using" "$(which find)" 1>&2
     fi
 fi
+
+# -- proceed
+# remove the old list of files.
+rm -f .etags-make-files.txt
+
+# Search in all specified directory to build the list of
+# files in the file '.etags-make-files.txt'.
+
+printf -- "%s - Processing %s/ ...\n" "${pgm_name}" "$(pwd)" 1>&2
+
+if [ -z "$1" ]; then
+    dirname="."
+    search
+else
+    for dirname in "$@"; do
+        search
+    done
+fi
+
+
+# Then run etags on these files, and sort them in the etags file
+sort < .etags-make-files.txt | uniq >  .etags-make-files.1.txt
+rm -f .etags-make-files.txt
+mv .etags-make-files.1.txt .etags-make-files.txt
+run__etags__make < .etags-make-files.txt
+
 file_count="$(wc -l .etags-make-files.txt | awk '{print $1}')"
-printf "%s files found and processed. List stored in: .etags-make-files.txt\n" "${file_count}"
+printf "\
+%s - %s files found and processed.
+           Created: %s/TAGS
+           Scanned file list stored in: %s/.etags-make-files.txt
+" "${pgm_name}" "${file_count}" "$(pwd)" "$(pwd)" 1>&2
 
 # -----------------------------------------------------------------------------
 # Local Variables:
