Re-organize code using common layout
In the future lots of this code could be placed in common files.
Starting the refactoring.

diff --git a/bin/etags-c b/bin/etags-c
--- a/bin/etags-c
+++ b/bin/etags-c
@@ -4,7 +4,7 @@
 #  Purpose   : Build Emacs Tags file for C/C++ source code files.
 #  Created   : Monday, November  9 2020.
 #  Author    : Pierre Rouleau <prouleau001@gmail.com>
-#  Time-stamp: <2025-04-24 16:54:17 EDT, updated by Pierre Rouleau>
+#  Time-stamp: <2025-04-24 18:48:05 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 #  Module Description
 #  ------------------
@@ -240,7 +240,7 @@ search_with_fd()
               -e .inl    \
               -e .M      \
               -e .pdb    \
-             . "$dirname" | tee -a .etags-c-files.txt
+             "$dirname" | tee -a .etags-c-files.txt
 }
 
 search()
@@ -262,10 +262,10 @@ search()
 
 if [ -n "$ETAGS_FILE_LIST" ]; then
     if [ "$ETAGS_FILE_LIST" = ".etags-c-files.txt" ]; then
-        echo "Error! Do NOT set ETAGS_FILE_LIST to .etags-c-files.txt"
+        echo "Error! Do NOT set ETAGS_FILE_LIST to .etags-c-files.txt" 1>&2
         exit 1
     fi
-    echo "Using the file list identified by ETAGS_FILE_LIST: $ETAGS_FILE_LIST"
+    echo "Using the file list identified by ETAGS_FILE_LIST: $ETAGS_FILE_LIST" 1>&2
     cp "$ETAGS_FILE_LIST" .etags-c-files.txt
     run__etags_c < "$ETAGS_FILE_LIST"
 else
