Cleanup, make all options available on almost all comments.
Also add the ability to backup the old .etags file and restore it when the new
search does not find anything.

diff --git a/bin/etags-autotools b/bin/etags-autotools
--- a/bin/etags-autotools
+++ b/bin/etags-autotools
@@ -4,7 +4,7 @@
 #  Purpose   : Build Emacs Tags file for GNU Autotools source code files.
 #  Created   : Thursday, June 6, 2024
 #  Author    : Pierre Rouleau <prouleau001@gmail.com>
-#  Time-stamp: <2025-04-25 09:25:10 EDT, updated by Pierre Rouleau>
+#  Time-stamp: <2025-04-25 13:50:29 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 #  Module Description
 #  ------------------
@@ -36,10 +36,12 @@
 #   other ctags command.
 
 # ----------------------------------------------------------------------------
-#  Code
-#  ----
+# Code
+# ----
 
 pgm_name="$(basename "$0")"
+etags_flist_fname=.etags-autotools-files.txt
+etags_flist_envvar_fname="$ETAGS_FILE_LIST_FOR_AUTOTOOLS"
 
 print_usage()
 {
@@ -53,11 +55,14 @@ print_usage()
   • Print this help information.
 
  Usage: %s [DIRPATH ...]
+        %s [--list=FILENAME]
 
   • [Re]build an etags-compliant TAGS file in current directory
     for the GNU Autotool and GNU Make source code files found:
     - in the DIRPATH directory tree(s) identified on the command line, or
-      the current directory if none is specified.
+      the current directory if none is specified, or
+    - in the list provided in the FILENAME specified by the --list option, or
+    - specified by the ETAGS_FILE_LIST_FOR_AUTOTOOLS environment variable.
   • Follows symbolic links both for directories and files.
   • Uses Universal Ctags to build the TAGS file by default.
     Emacs etags does not support M4, autoconf and automake.
@@ -83,7 +88,7 @@ print_usage()
  • The only output on stdout is the list of files found.
     This allows this script to be used as the first in a pipe
     to do other processing with the list of files found.
-" "$pgm_name" "$pgm_name" "$pgm_name"
+" "$pgm_name" "$pgm_name" "$pgm_name" "$pgm_name"
     if [ "$ETAGS_USE_FIND" = "1" ]; then
         printf -- "
 ⚠️   ETAGS_USE_FIND is currently set to 1, forcing the use of 'find'!
@@ -95,8 +100,16 @@ print_usage()
 }
 
 # --
+# run__etags__autotools -- run ctags on a set of files
+# ---------------------
+#
+# Use ctags to parse the source code files.
+# Ideally that would be the latest version of Universal ctags
+# from https://github.com/universal-ctags/ctags#readme as opposed to the
+# old and currently un-maintained Exeburant ctags.
+# Generate Emacs-compliant TAGS file.
 
-run__etags__make()
+run__etags__autotools()
 {
     # Expects no argument, but expects a list of files to parse on stdin.
     xargs ctags --output-format=etags
@@ -108,6 +121,7 @@ run__etags__make()
 if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
     print_usage
     if [ "$#" = "1" ]; then
+        # help requested explicitly with right amount of args: no error.
         exit 0
     else
         exit  1
@@ -133,43 +147,28 @@ elif ! ctags --version | grep -q "Universal Ctags"; then
 fi
 
 # --
-# Check the validity of directory names specified as arguments.
-# Ensure that each directory specified on the command line
-# exists.  Also ensure that a directory name is not specified more
-# than once.  Use the realpath of that directory name when comparing.
+#  Check --list option to extract list of autotools files.
 
-dpaths=
-for dname in "$@"; do
-    if [ ! -d "${dname}" ]; then
-        printf -- "Specified directory does not exists: %s\n" "${dname}"
-        exit 2
-    fi
-    dpath="$(realpath "${dname}")"
-    for dp in ${dpaths}; do
-        if [ "$dp" = "$dpath" ]; then
-            printf -- "Multiple entry of directory: %s\n" "${dname}"
-            exit 3
+case "$1" in
+    --list=*)
+    # extract the file name from the --list= option
+        fname="$(echo "$1" | sed 's/--list=//g')"
+        if [ ! -f "${fname}" ]; then
+            printf -- "\
+*** ERROR: %s: specified list file does not exist: %s
+" "${pgm_name}" "${fname}" 1>&2
+            exit 1
+        else
+            etags_flist_envvar_fname="${fname}"
+            shift
         fi
-        # check if new entry is a sub-directory of an exiting entry
-        case "${dpath}" in
-            "${dp}/"*)
-                printf -- "%s is a sub-dir of already specified %s\n" "${dname}" "${dp}"
-                exit 3
-                ;;
-        esac
-        # check if new entry is a parent directory of an existing entry
-        case "${dp}" in
-            "${dpath}/"*)
-                printf -- "%s is a parent dir of already specified %s\n" "${dname}" "${dp}"
-                exit 3
-                ;;
-        esac
+        ;;
+esac
 
-    done
-    dpaths="${dpaths} ${dpath}"
-done
-
-# --
+# ----------------------------------------------------------------------------
+# Define a function that searches into 1 directory
+# and accumulates the list of found files into the
+# file '.etags-autotools-files.txt'.
 
 # Identify options
 case $(uname) in
@@ -185,29 +184,25 @@ case $(uname) in
         ;;
 esac
 
-# Define a function that searches into 1 directory
-# and accumulates the list of found files into the
-# file '.etags-autotools-files.txt'.
-
 search_with_find()
 {
     # Arg: dirname : name of directory tree to search
 
     # Search for make files
     # and for the M4, autoconf and automake files
-    find -L ${find_path_option} "$dirname" \( \
-             -name "Makefile" \
-         -or -name "makefile" \
-         -or -name "GNUMakefile" \
-         -or -name "Makefile.in" \
-         -or -name "Makefile.am" \
-         -or -name "*\.mk" \
-         -or -name "*\.mak" \
-         -or -name "*\.m4" \
-         -or -name "configure.ac" \
-         -or -name "config.h.in" \
-         -or -name "config.h" \
-         \) -print | tee -a .etags-autotools-files.txt
+    find -L ${find_path_option} "$dirname" \
+         \(  -name "Makefile"              \
+         -or -name "makefile"              \
+         -or -name "GNUMakefile"           \
+         -or -name "Makefile.in"           \
+         -or -name "Makefile.am"           \
+         -or -name "*\.mk"                 \
+         -or -name "*\.mak"                \
+         -or -name "*\.m4"                 \
+         -or -name "configure.ac"          \
+         -or -name "config.h.in"           \
+         -or -name "config.h"              \
+         \) -print | tee -a "${etags_flist_fname}"
 }
 
 search_with_fd()
@@ -217,12 +212,14 @@ search_with_fd()
 
     # Search for make files
     # and for the M4, autoconf and automake files
+    # Note: fd expects a regexp-string.  Use '' if none is required, otherwise
+    #       it will take the directory name as a regexp...
     ${fd_pgm} -L --type f '((makefile)|((GNU)?Makefile(.((in)|(am)))?))$' \
-              '' "$dirname" | tee -a .etags-autotools-files.txt
+               "$dirname" | tee -a "${etags_flist_fname}"
     ${fd_pgm} -L --type f -e .m4 -e .mk -e .mak\
-              '' "$dirname" | tee -a .etags-autotools-files.txt
+              '' "$dirname" | tee -a "${etags_flist_fname}"
     ${fd_pgm} -L --type f '((configure.ac)|(config.h.in)|(config.h))$' \
-              '' "$dirname" | tee -a .etags-autotools-files.txt
+               "$dirname" | tee -a "${etags_flist_fname}"
 }
 
 search()
@@ -241,67 +238,124 @@ search()
 }
 
 # --
-# First prepare environment
+# Proceed
 
-# Select the method to search for files.
-# - Try to use fd or fdfind if they exist,
-#   otherwise use find.
-# - Echo the actual program used to find files (on stderr).
-if [ "$ETAGS_USE_FIND" = "1" ]; then
-    search_with='find'
-    echo "- ETAGS_USE_FIND forces the use of find!" 1>&2
-    echo "-> Using" "$(which find)"                 1>&2
-else
-    if [ -x "$(command -v fdfind)" ]; then
-        search_with='fd'
-        fd_pgm=fdfind
-        echo "-> Using" "$(which fdfind)"    1>&2
-        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
-
-    elif [ -x "$(command -v fd)" ]; then
-        search_with='fd'
-        fd_pgm=fd
-        echo "-> Using" "$(which fd)" 1>&2
-        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
-    else
-        search_with='find'
-        echo "-> Using" "$(which find)" 1>&2
+if [ -n "${etags_flist_envvar_fname}" ]; then
+    if [ "${etags_flist_envvar_fname}" = "${etags_flist_fname}" ]; then
+        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_AUTOTOOLS to %s\n" "${pgm_name}" "${etags_flist_fname}"1>&2
+        exit 1
     fi
-fi
-
-# -- proceed
-# remove the old list of files.
-rm -f .etags-autotools-files.txt
-
-# Search in all specified directory to build the list of
-# files in the file '.etags-autotools-files.txt'.
-
-printf -- "%s - Processing %s/ ...\n" "${pgm_name}" "$(pwd)" 1>&2
-
-if [ -z "$1" ]; then
-    dirname="."
-    search
+    printf -- "Using the file list identified by ETAGS_FILE_LIST_FOR_AUTOTOOLS: %s\n" "${etags_flist_envvar_fname}" 1>&2
+    cp "${etags_flist_envvar_fname}" "${etags_flist_fname}"
+    run__etags__autotools < "${etags_flist_envvar_fname}"
 else
-    for dirname in "$@"; do
-        search
+    # Check the validity of directory names specified as arguments.
+    # Ensure that each directory specified on the command line
+    # exists.  Also ensure that a directory name is not specified more
+    # than once.  Use the realpath of that directory name when comparing.
+    # Exit on the first error detected.
+    dpaths=
+    for dname in "$@"; do
+        if [ ! -d "${dname}" ]; then
+            printf -- "Specified directory does not exists: %s\n" "${dname}" 1>&2
+            exit 2
+        fi
+        dpath="$(realpath "${dname}")"
+        for dp in ${dpaths}; do
+            if [ "$dp" = "$dpath" ]; then
+                printf -- "Multiple entry of directory: %s\n" "${dname}" 1>&2
+                exit 3
+            fi
+            # check if new entry is a sub-directory of an exiting entry
+            case "${dpath}" in
+                "${dp}/"*)
+                    printf -- "%s is a sub-dir of already specified %s\n" "${dname}" "${dp}" 1>&2
+                    exit 3
+                    ;;
+            esac
+            # check if new entry is a parent directory of an existing entry
+            case "${dp}" in
+                "${dpath}/"*)
+                    printf -- "%s is a parent dir of already specified %s\n" "${dname}" "${dp}" 1>&2
+                    exit 3
+                    ;;
+            esac
+        done
+        dpaths="${dpaths} ${dpath}"
     done
+
+    # --
+    # First prepare environment
+    # Select the method to search for files.
+    # - Try to use fd or fdfind if they exist,
+    #   otherwise use find.
+    # - Echo the actual program used to find files (on stderr).
+    if [ "$ETAGS_USE_FIND" = "1" ]; then
+        search_with='find'
+        echo "- ETAGS_USE_FIND forces the use of find!" 1>&2
+        echo "-> Using" "$(which find)"                 1>&2
+    else
+        if [ -x "$(command -v fdfind)" ]; then
+            search_with='fd'
+            fd_pgm=fdfind
+            echo "-> Using" "$(which fdfind)" 1>&2
+            echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
+        elif [ -x "$(command -v fd)" ]; then
+            search_with='fd'
+            fd_pgm=fd
+            echo "-> Using" "$(which fd)" 1>&2
+            echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
+        else
+            search_with='find'
+            echo "-> Using" "$(which find)" 1>&2
+        fi
+    fi
+
+    printf -- "No list of files identified by ETAGS_FILE_LIST_FOR_AUTOTOOLS.\n" 1>&2
+    printf -- "Files found printed in found order (not necessarily in sorted order)\n" 1>&2
+
+    # -- proceed
+    # Rename the old list of files if it exists
+    if [ -e "${etags_flist_fname}" ]; then
+        mv "${etags_flist_fname}" "${etags_flist_fname}.backup"
+    fi
+
+    # Search in all specified directory to build the list of
+    # files in the file '.etags-autotools-files.txt'.
+    if [ -z "$1" ]; then
+        dirname="."
+        search
+    else
+        for dirname in "$@"; do
+            search
+        done
+    fi
+
+    # Then run etags on these files, and sort them in the etags file
+    sort < "${etags_flist_fname}" | uniq >  "${etags_flist_fname}.new"
+    rm -f "${etags_flist_fname}"
+    mv "${etags_flist_fname}.new" "${etags_flist_fname}"
+    run__etags__autotools < "${etags_flist_fname}"
 fi
 
+file_count="$(wc -l "${etags_flist_fname}" | awk '{print $1}')"
+if [ "$file_count" = "0" ]; then
+    # restore the old list of files.
+    rm -rf "${etags_flist_fname}"
+    if [ -e "${etags_flist_fname}.backup" ]; then
+        mv "${etags_flist_fname}.backup"  "${etags_flist_fname}"
+    fi
+    printf -- "No files found. %s and TAGS files untouched.\n" "${etags_flist_fname}"  1>&2
+    exit 1
+else
+  rm -rf "${etags_flist_fname}.backup"
+  printf "\
+  %s - %s files found and processed.
+             Created: %s/TAGS
+             Scanned file list stored in: %s/%s\n" "${pgm_name}" "${file_count}" "$(pwd)" "$(pwd)" "${etags_flist_fname}" 1>&2
+fi
 
-# Then run etags on these files, and sort them in the etags file
-sort < .etags-autotools-files.txt | uniq >  .etags-autotools-files.1.txt
-rm -f .etags-autotools-files.txt
-mv .etags-autotools-files.1.txt .etags-autotools-files.txt
-run__etags__make < .etags-autotools-files.txt
-
-file_count="$(wc -l .etags-autotools-files.txt | awk '{print $1}')"
-printf "\
-%s - %s files found and processed.
-           Created: %s/TAGS
-           Scanned file list stored in: %s/.etags-autotools-files.txt
-" "${pgm_name}" "${file_count}" "$(pwd)" "$(pwd)" 1>&2
-
-# -----------------------------------------------------------------------------
+# ----------------------------------------------------------------------------
 # Local Variables:
 # sh-shell: sh
 # End:
diff --git a/bin/etags-c b/bin/etags-c
--- a/bin/etags-c
+++ b/bin/etags-c
@@ -4,7 +4,7 @@
 #  Purpose   : Build Emacs Tags file for C/C++ source code files.
 #  Created   : Monday, November  9 2020.
 #  Author    : Pierre Rouleau <prouleau001@gmail.com>
-#  Time-stamp: <2025-04-25 09:25:27 EDT, updated by Pierre Rouleau>
+#  Time-stamp: <2025-04-25 13:49:34 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 #  Module Description
 #  ------------------
@@ -23,7 +23,7 @@
 # ----------------------------------------------------------------------------
 #  Dependencies
 #  ------------
-#
+
 # - Uses fd (also named fdfind in some Linux distros like Mint) if it is
 #   available.  See URL:  https://github.com/sharkdp/fd .
 # - if fd/fdfind is not available, use find instead.
@@ -41,14 +41,17 @@
 #   Universal Ctags executable file.
 
 # ----------------------------------------------------------------------------
-#  Code
-#  ----
+# Code
+# ----
 
 pgm_name="$(basename "$0")"
+etags_flist_fname=.etags-c-files.txt
+etags_flist_envvar_fname="$ETAGS_FILE_LIST_FOR_C"
+
 print_usage()
 {
     printf -- "
-etags-c: build a etags-compliant TAGS file in the current directory
+%s: build a etags-compliant TAGS file in the current directory
          for all C and C++ source code files in the directory trees
          specified on the command line.
 
@@ -56,21 +59,27 @@ etags-c: build a etags-compliant TAGS file in the current directory
 
   • Print this help information.
 
- Usage: %s [DIRPATH ...]
-        %s [--list=FILENAME]
+ Usage: %s [-u] [DIRPATH ...]
+        %s [-u] [--list=FILENAME]
 
   • [Re]build an etags-compliant TAGS file in current directory
     for the C/C++ code & header files found:
     - in the DIRPATH directory tree(s) identified on the command line, or
       the current directory if none is specified,
     - in the list provided in the FILENAME specified by the --list option, or
-    - specified by the ETAGS_FILE_LIST environment variable.
+    - specified by the ETAGS_FILE_LIST_FOR_C environment variable.
   • Follows symbolic links both for directories and files.
+  • Uses etags to build the TAGS file by default, but
+    -u : force use Universal Ctags (ctags) instead of etags.
+  • Set ETAGS_USE_UCTAGS to 1 or the absolute path of
+    Universal Ctags executable file to force using Universal Ctags.
+    When setting it to 1, the ctags found in PATH is expected
+    to be Universal Ctags.
   • Overwrites any TAGS file in the current directory.
   • Stores the names of inspected files in the file named
      .etags-c-files.txt in the current directory.
   • Identifies the C/C++ files using one of the following methods:
-    • If ETAGS_FILE_LIST environment variable exists, it uses it as
+    • If ETAGS_FILE_LIST_FOR_C environment variable exists, it uses it as
       the name of a file that holds a list of C/C++ files to parse.
       The name of this file can be anything except .etags-c-files.txt
       and it must exists. If it does not: exists with an error.
@@ -94,7 +103,7 @@ etags-c: build a etags-compliant TAGS file in the current directory
      • The path of the find program used and when repository ignore files
        are skipped from the scan.
      • A count of found files, and the name of the file that holds them.
-" "$pgm_name" "$pgm_name" "$pgm_name"
+" "$pgm_name" "$pgm_name" "$pgm_name" "$pgm_name"
     if [ "$ETAGS_USE_FIND" = "1" ]; then
         printf -- "
 ⚠️   ETAGS_USE_FIND is currently set to 1, forcing the use of 'find'!
@@ -106,7 +115,7 @@ etags-c: build a etags-compliant TAGS file in the current directory
 }
 
 # --
-# run__etags_c -- run etags or ctags on a set of files
+# run__etags__c -- run etags or ctags on a set of files
 # ------------
 #
 # Use etags to parse the source code files unless ETAGS_USE_UCTAGS
@@ -117,21 +126,21 @@ etags-c: build a etags-compliant TAGS file in the current directory
 # When using Emacs, Emacs provides its own ctags that is essentially etags.
 # Etags generates a tag file format a little different and better suited for Emacs.
 
-run__etags_c()
+run__etags__c()
 {
     # Expects no argument, but expects a list of files to parse on stdin.
 
     if [ -n "$ETAGS_USE_UCTAGS" ]; then
         if [ "$ETAGS_USE_UCTAGS" = "1" ]; then
             xargs ctags --output-format=etags
-            printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n" "$(which ctags)"
+            printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n" "$(which ctags)" 1>&2
         elif [ -x "$ETAGS_USE_UCTAGS" ]; then
             xargs "$ETAGS_USE_UCTAGS" --output-format=etags
-            printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n"  "$ETAGS_USE_UCTAGS"
+            printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n"  "$ETAGS_USE_UCTAGS" 1>&2
         else
-            printf -- "*** ERROR: %s: invalid ETAGS_USE_UCTAGS value\n" "${pgm_name}"
-            printf -- "***  ETAGS_USE_UCTAGS : %s\n" "$ETAGS_USE_UCTAGS"
-            printf -- "***  This is not 1 nor a valid executable file name.\n"
+            printf -- "*** ERROR: %s: invalid ETAGS_USE_UCTAGS value\n" "${pgm_name}" 1>&2
+            printf -- "***  ETAGS_USE_UCTAGS : %s\n" "$ETAGS_USE_UCTAGS" 1>&2
+            printf -- "***  This is not 1 nor a valid executable file name.\n" 1>&2
             exit 4
         fi
     else
@@ -139,7 +148,6 @@ run__etags_c()
         etags --class-qualify -
     fi
 }
-
 
 # --
 # Check validity of arguments
@@ -154,6 +162,21 @@ if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
     fi
 fi
 
+# Check -u option to force use of universal ctags
+if [ "$1" = "-u" ]; then
+    if [ -z "$ETAGS_USE_UCTAGS" ]; then
+        printf -- "%s: -u option requests use of Universal Ctags.\n" "${pgm_name}" 1>&2
+        ETAGS_USE_UCTAGS=1
+    else
+        printf -- "%s: -u option not necessary (but does no harm).\n" "${pgm_name}" 1>&2
+        printf -- " ETAGS_USE_UCTAGS is already set to: %s\n" "$ETAGS_USE_UCTAGS" 1>&2
+    fi
+    shift
+fi
+
+# --
+#  Check --list option to extract list of C/C++ files.
+
 case "$1" in
     --list=*)
     # extract the file name from the --list= option
@@ -161,20 +184,33 @@ case "$1" in
         if [ ! -f "${fname}" ]; then
             printf -- "\
 *** ERROR: %s: specified list file does not exist: %s
-" "${pgm_name}" "${fname}"
+" "${pgm_name}" "${fname}" 1>&2
             exit 1
         else
-            ETAGS_FILE_LIST="${fname}"
+            etags_flist_envvar_fname="${fname}"
             shift
         fi
         ;;
 esac
 
-# --
-
+# ----------------------------------------------------------------------------
 # Define a function that searches into 1 directory
 # and accumulates the list of found files into the
 # file '.etags-c-files.txt'.
+
+# Identify options
+case $(uname) in
+    Darwin)
+        find_path_option='-f'
+        ;;
+    Linux)
+        find_path_option=
+        ;;
+    *)
+        printf -- "*** ERROR: %s:  Error Operating System, %s, is not supported!\n" "${pgm_name}"  "$(uname)" 1>&2
+        exit 1
+        ;;
+esac
 
 search_with_find()
 {
@@ -198,7 +234,7 @@ search_with_find()
          -or -name "*.inl"       \
          -or -name "*.M"         \
          -or -name "*.pdb"       \
-         \)  -print | tee -a .etags-c-files.txt
+         \)  -print | tee -a "${etags_flist_fname}"
 }
 
 search_with_fd()
@@ -236,7 +272,7 @@ search_with_fd()
               -e .inl    \
               -e .M      \
               -e .pdb    \
-             '' "$dirname" | tee -a .etags-c-files.txt
+             '' "$dirname" | tee -a "${etags_flist_fname}"
 }
 
 search()
@@ -255,21 +291,22 @@ search()
 }
 
 # --
+# Proceed
 
-if [ -n "$ETAGS_FILE_LIST" ]; then
-    if [ "$ETAGS_FILE_LIST" = ".etags-c-files.txt" ]; then
-        echo "Error! Do NOT set ETAGS_FILE_LIST to .etags-c-files.txt" 1>&2
+if [ -n "${etags_flist_envvar_fname}" ]; then
+    if [ "${etags_flist_envvar_fname}" = "${etags_flist_fname}" ]; then
+        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_C to %s\n" "${pgm_name}" "${etags_flist_fname}"1>&2
         exit 1
     fi
-    echo "Using the file list identified by ETAGS_FILE_LIST: $ETAGS_FILE_LIST" 1>&2
-    cp "$ETAGS_FILE_LIST" .etags-c-files.txt
-    run__etags_c < "$ETAGS_FILE_LIST"
+    printf -- "Using the file list identified by ETAGS_FILE_LIST_FOR_C: %s\n" "${etags_flist_envvar_fname}" 1>&2
+    cp "${etags_flist_envvar_fname}" "${etags_flist_fname}"
+    run__etags__c < "${etags_flist_envvar_fname}"
 else
-    # Use the directory names provided on command line.
-    # Check their validity.
+    # Check the validity of directory names specified as arguments.
     # Ensure that each directory specified on the command line
     # exists.  Also ensure that a directory name is not specified more
     # than once.  Use the realpath of that directory name when comparing.
+    # Exit on the first error detected.
     dpaths=
     for dname in "$@"; do
         if [ ! -d "${dname}" ]; then
@@ -301,15 +338,12 @@ else
         dpaths="${dpaths} ${dpath}"
     done
 
-    echo "No list of files identified by ETAGS_FILE_LIST." 1>&2
-    echo "- Building the list of source files."            1>&2
-
-    # Find the files, pass their names to etags which creates the TAGS file.
-    # To find the files, try to use 'fd' or 'fdfind' if they exist,
-    # otherwise use 'find'.  Echo the actual program used to find the files.
-    # Search for all possible C and C++ file extensions in the directory tree.
-
-    # - Identify how to search files
+    # --
+    # First prepare environment
+    # Select the method to search for files.
+    # - Try to use fd or fdfind if they exist,
+    #   otherwise use find.
+    # - Echo the actual program used to find files (on stderr).
     if [ "$ETAGS_USE_FIND" = "1" ]; then
         search_with='find'
     else
@@ -323,21 +357,6 @@ else
             search_with='find'
         fi
     fi
-
-    # Identify options
-    case $(uname) in
-        Darwin)
-            find_path_option='-f'
-            ;;
-        Linux)
-            find_path_option=
-            ;;
-        *)
-            printf -- "etags-c ** Error Operating System, %s, is not supported!\n" "$(uname)" 1>&2
-            exit 1
-            ;;
-    esac
-
     # Print operating information on stderr.
     case "$search_with" in
         find)
@@ -357,12 +376,17 @@ else
             exit 1
             ;;
     esac
+    printf --  "No list of files identified by ETAGS_FILE_LIST_FOR_C.\n" 1>&2
     printf -- "Files found printed in found order (not necessarily in sorted order)\n" 1>&2
 
-    # delete old list
-    rm -f .etags-c-files.txt
+    # -- proceed
+    # Rename the old list of files if it exists
+    if [ -e "${etags_flist_fname}" ]; then
+        mv "${etags_flist_fname}" "${etags_flist_fname}.backup"
+    fi
+
     # Search in all specified directory to build the list of
-    # files in the file '.etags-c-files.txt'.
+    # files in the file '"${etags_flist_fname}"'.
     if [ -z "$1" ]; then
         dirname="."
         search
@@ -373,14 +397,28 @@ else
     fi
 
     # Then run etags on these files, and sort them in the etags file
-    sort < .etags-c-files.txt | uniq >  .etags-c-files.1.txt
-    rm -f .etags-c-files.txt
-    mv .etags-c-files.1.txt .etags-c-files.txt
-    run__etags_c < .etags-c-files.txt
+    sort < "${etags_flist_fname}" | uniq >  "${etags_flist_fname}.new"
+    rm -f "${etags_flist_fname}"
+    mv "${etags_flist_fname}.new" "${etags_flist_fname}"
+    run__etags__rust < "${etags_flist_fname}"
 fi
 
-file_count="$(wc -l .etags-c-files.txt | awk '{print $1}')"
-printf -- "%s files found and processed. List stored in: .etags-c-files.txt\n" "${file_count=}" 1>&2;
+file_count="$(wc -l "${etags_flist_fname}" | awk '{print $1}')"
+if [ "$file_count" = "0" ]; then
+    # restore the old list of files.
+    rm -rf "${etags_flist_fname}"
+    if [ -e "${etags_flist_fname}.backup" ]; then
+        mv "${etags_flist_fname}.backup"  "${etags_flist_fname}"
+    fi
+    printf -- "No files found. %s and TAGS files untouched.\n" "${etags_flist_fname}"  1>&2
+    exit 1
+else
+  rm -rf "${etags_flist_fname}.backup"
+  printf "\
+  %s - %s files found and processed.
+             Created: %s/TAGS
+             Scanned file list stored in: %s/%s\n" "${pgm_name}" "${file_count}" "$(pwd)" "$(pwd)" "${etags_flist_fname}" 1>&2
+fi
 
 # ----------------------------------------------------------------------------
 # Local Variables:
diff --git a/bin/etags-el b/bin/etags-el
--- a/bin/etags-el
+++ b/bin/etags-el
@@ -4,7 +4,7 @@
 #  Purpose   : Build Emacs Tags file for Emacs Lisp and C source code files.
 #  Created   : Thursday, October 15 2020.
 #  Author    : Pierre Rouleau <prouleau001@gmail.com>
-#  Time-stamp: <2025-04-25 09:25:48 EDT, updated by Pierre Rouleau>
+#  Time-stamp: <2025-04-25 14:39:28 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 #  Module Description
 #  ------------------
@@ -37,6 +37,8 @@
 #  ----
 
 pgm_name="$(basename "$0")"
+etags_flist_fname=.etags-el-files.txt
+etags_flist_envvar_fname="$ETAGS_FILE_LIST_FOR_ELISP"
 
 print_usage()
 {
@@ -50,13 +52,16 @@ print_usage()
   • Print this help information.
 
  Usage: %s [--in=TARGET-DIRPATH] [DIRPATH ...]
+        %s [--in=TARGET-DIRPATH] [--list=FILENAME]
 
   • [Re]build an etags-compliant TAGS file in specified
     TARGET-DIRPATH or current directory for the Emacs Lisp,
     C code & header files found:
     - in the DIRPATH directory tree(s) identified on the command line, or
-      the current directory if none is specified.
-    All operations are done with the current directory being
+      the current directory if none is specified, or
+    - in the list provided in the FILENAME specified by the --list option, or
+    - specified by the ETAGS_FILE_LIST_FOR_ELISP environment variable.
+  • All operations are done with the current directory being
     the TARGET-DIRPATH if specified, otherwise it's the current one.
     This means that when specifying TARGET-DIRPATH, all other
     DIRPATH are relative to that directory (if relative).
@@ -85,7 +90,7 @@ print_usage()
  • The only output on stdout is the list of files found.
     This allows this script to be used as the first in a pipe
     to do other processing with the list of files found.
-" "$pgm_name" "$pgm_name" "$pgm_name"
+" "$pgm_name" "$pgm_name" "$pgm_name" "$pgm_name"
     if [ "$ETAGS_USE_FIND" = "1" ]; then
         printf -- "
 ⚠️   ETAGS_USE_FIND is currently set to 1, forcing the use of 'find'!
@@ -97,6 +102,11 @@ print_usage()
 }
 
 # --
+# run__etags__el -- run etags on a set of files
+# --------------
+#
+# Use etags to parse the source code files.
+# Etags generates a tag file format a little different and better suited for Emacs.
 
 run__etags__el()
 {
@@ -121,69 +131,51 @@ if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
     fi
 fi
 
-case "$1" in
-    --in=*)
-        targetdir="$(echo "$1" | cut -c 6- | sed "s:~:$HOME:g")"
-        targetdir=$(realpath "${targetdir}")
-        if [ -d "${targetdir}" ]; then
-            cd "${targetdir}" || exit 1
-            shift
-        else
-            printf -- "\
+# Check other options
+options=2
+while [ "$options" -ge 1 ]; do
+    case "$1" in
+        --in=*)
+            targetdir="$(echo "$1" | cut -c 6- | sed "s:~:$HOME:g")"
+            targetdir=$(realpath "${targetdir}")
+            if [ -d "${targetdir}" ]; then
+                cd "${targetdir}" || exit 1
+                shift
+            else
+                printf -- "\
 *** ERROR: %s: invalid TARGET-DIRPATH: %s\n" "${pgm_name}" "${targetdir}" 1>&2
-            exit 1
-        fi
-        ;;
-    --)
-        shift
-        ;;
+                exit 1
+            fi
+            ;;
 
-    -*)
-        printf -- "\
+        --list=*)
+            # extract the file name from the --list= option
+            fname="$(echo "$1" | sed 's/--list=//g')"
+            if [ ! -f "${fname}" ]; then
+                printf -- "\
+*** ERROR: %s: specified list file does not exist: %s
+" "${pgm_name}" "${fname}" 1>&2
+                exit 1
+            else
+                etags_flist_envvar_fname="${fname}"
+                shift
+            fi
+            ;;
+
+        --)
+            shift
+            ;;
+
+        -*)
+            printf -- "\
 *** ERROR: %s: invalid options: %s\n" "${pgm_name}" "$1" 1>&2
-        exit 1
-        ;;
-esac
-
-# --
-# Check the validity of directory names specified as arguments.
-# Ensure that each directory specified on the command line
-# exists.  Also ensure that a directory name is not specified more
-# than once.  Use the realpath of that directory name when comparing.
-
-dpaths=
-for dname in "$@"; do
-    if [ ! -d "${dname}" ]; then
-        printf -- "Specified directory does not exists: %s\n" "${dname}" 1>&2
-        exit 2
-    fi
-    dpath="$(realpath "${dname}")"
-    for dp in ${dpaths}; do
-        if [ "$dp" = "$dpath" ]; then
-            printf -- "Multiple entry of directory: %s\n" "${dname}" 1>&2
-            exit 3
-        fi
-        # check if new entry is a sub-directory of an exiting entry
-        case "${dpath}" in
-            "${dp}/"*)
-                printf -- "%s is a sub-dir of already specified %s\n" "${dname}" "${dp}" 1>&2
-                exit 3
-                ;;
-        esac
-        # check if new entry is a parent directory of an existing entry
-        case "${dp}" in
-            "${dpath}/"*)
-                printf -- "%s is a parent dir of already specified %s\n" "${dname}" "${dp}" 1>&2
-                exit 3
-                ;;
-        esac
-
-    done
-    dpaths="${dpaths} ${dpath}"
+            exit 1
+            ;;
+    esac
+    options=$(( options - 1 ))
 done
 
-# --
-
+# ----------------------------------------------------------------------------
 # Define a function that searches into 1 directory
 # and accumulates the list of found files into the
 # file '.etags-el-files.txt'.
@@ -209,7 +201,7 @@ search_with_find()
          -or -name "*.el.gz" \
          -or -name "*.[ch]"  \
          -or -name "*.[ch].gz" \
-         \)  -print | tee -a .etags-el-files.txt
+         \)  -print | tee -a "${etags_flist_fname}"
 }
 
 search_with_fd()
@@ -220,7 +212,7 @@ search_with_fd()
     ${fd_pgm} -L --type f -e .el -e .el.gz \
               -e .c -e .c.gz \
               -e .h -e .h.gz \
-              '' "$dirname" | tee -a .etags-el-files.txt
+              '' "$dirname" | tee -a "${etags_flist_fname}"
 }
 
 search()
@@ -238,67 +230,125 @@ search()
     esac
 }
 
-
 # --
-# First prepare environment
-# Select the method to search for files.
-# - Try to use fd or fdfind if they exist,
-#   otherwise use find.
-# - Echo the actual program used to find files (on stderr).
-if [ "$ETAGS_USE_FIND" = "1" ]; then
-    search_with='find'
-    echo "- ETAGS_USE_FIND forces the use of find!" 1>&2
-    echo "-> Using" "$(which find)"                 1>&2
-else
-    if [ -x "$(command -v fdfind)" ]; then
-        search_with='fd'
-        fd_pgm=fdfind
-        echo "-> Using" "$(which fdfind)" 1>&2
-        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
-    elif [ -x "$(command -v fd)" ]; then
-        search_with='fd'
-        fd_pgm=fd
-        echo "-> Using" "$(which fd)" 1>&2
-        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
-    else
-        search_with='find'
-        echo "-> Using" "$(which find)" 1>&2
+# Proceed
+
+if [ -n "${etags_flist_envvar_fname}" ]; then
+    if [ "${etags_flist_envvar_fname}" = "${etags_flist_fname}" ]; then
+        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_ELISP to %s\n" "${pgm_name}" "${etags_flist_fname}"1>&2
+        exit 1
     fi
-fi
-
-# -- proceed
-# remove the old list of files.
-rm -f .etags-el-files.txt
-
-# Search in all specified directory to build the list of
-# files in the file '.etags-el-files.txt'.
-
-printf -- "%s - Processing %s/ ...\n" "${pgm_name}" "$(pwd)" 1>&2
-
-if [ -z "$1" ]; then
-    dirname="."
-    search
+    printf -- "Using the file list identified by ETAGS_FILE_LIST_FOR_ELISP: %s\n" "${etags_flist_envvar_fname}" 1>&2
+    cp "${etags_flist_envvar_fname}" "${etags_flist_fname}"
+    run__etags__el < "${etags_flist_envvar_fname}"
 else
-    for dirname in "$@"; do
-        search
+    # Check the validity of directory names specified as arguments.
+    # Ensure that each directory specified on the command line
+    # exists.  Also ensure that a directory name is not specified more
+    # than once.  Use the realpath of that directory name when comparing.
+    # Exit on the first error detected.
+    dpaths=
+    for dname in "$@"; do
+        if [ ! -d "${dname}" ]; then
+            printf -- "Specified directory does not exists: %s\n" "${dname}" 1>&2
+            exit 2
+        fi
+        dpath="$(realpath "${dname}")"
+        for dp in ${dpaths}; do
+            if [ "$dp" = "$dpath" ]; then
+                printf -- "Multiple entry of directory: %s\n" "${dname}" 1>&2
+                exit 3
+            fi
+            # check if new entry is a sub-directory of an exiting entry
+            case "${dpath}" in
+                "${dp}/"*)
+                    printf -- "%s is a sub-dir of already specified %s\n" "${dname}" "${dp}" 1>&2
+                    exit 3
+                    ;;
+            esac
+            # check if new entry is a parent directory of an existing entry
+            case "${dp}" in
+                "${dpath}/"*)
+                    printf -- "%s is a parent dir of already specified %s\n" "${dname}" "${dp}" 1>&2
+                    exit 3
+                    ;;
+            esac
+        done
+        dpaths="${dpaths} ${dpath}"
     done
+
+    # --
+    # First prepare environment
+    # Select the method to search for files.
+    # - Try to use fd or fdfind if they exist,
+    #   otherwise use find.
+    # - Echo the actual program used to find files (on stderr).
+    if [ "$ETAGS_USE_FIND" = "1" ]; then
+        search_with='find'
+        echo "- ETAGS_USE_FIND forces the use of find!" 1>&2
+        echo "-> Using" "$(which find)"                 1>&2
+    else
+        if [ -x "$(command -v fdfind)" ]; then
+            search_with='fd'
+            fd_pgm=fdfind
+            echo "-> Using" "$(which fdfind)" 1>&2
+            echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
+        elif [ -x "$(command -v fd)" ]; then
+            search_with='fd'
+            fd_pgm=fd
+            echo "-> Using" "$(which fd)" 1>&2
+            echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
+        else
+            search_with='find'
+            echo "-> Using" "$(which find)" 1>&2
+        fi
+    fi
+
+    printf -- "No list of files identified by ETAGS_FILE_LIST_FOR_ELISP.\n" 1>&2
+    printf -- "Files found printed in found order (not necessarily in sorted order)\n" 1>&2
+
+    # -- proceed
+    # Rename the old list of files if it exists
+    if [ -e "${etags_flist_fname}" ]; then
+        mv "${etags_flist_fname}" "${etags_flist_fname}.backup"
+    fi
+
+    # Search in all specified directory to build the list of
+    # files in the file '.etags-el-files.txt'.
+    if [ -z "$1" ]; then
+        dirname="."
+        search
+    else
+        for dirname in "$@"; do
+            search
+        done
+    fi
+
+    # Then run etags on these files, and sort them in the etags file
+    sort < "${etags_flist_fname}" | uniq >  "${etags_flist_fname}.new"
+    rm -f "${etags_flist_fname}"
+    mv "${etags_flist_fname}.new" "${etags_flist_fname}"
+    run__etags__el < "${etags_flist_fname}"
 fi
 
+file_count="$(wc -l "${etags_flist_fname}" | awk '{print $1}')"
+if [ "$file_count" = "0" ]; then
+    # restore the old list of files.
+    rm -rf "${etags_flist_fname}"
+    if [ -e "${etags_flist_fname}.backup" ]; then
+        mv "${etags_flist_fname}.backup"  "${etags_flist_fname}"
+    fi
+    printf -- "No files found. %s and TAGS files untouched.\n" "${etags_flist_fname}"  1>&2
+    exit 1
+else
+  rm -rf "${etags_flist_fname}.backup"
+  printf "\
+  %s - %s files found and processed.
+             Created: %s/TAGS
+             Scanned file list stored in: %s/%s\n" "${pgm_name}" "${file_count}" "$(pwd)" "$(pwd)" "${etags_flist_fname}" 1>&2
+fi
 
-# Then run etags on these files, and sort them in the etags file
-sort < .etags-el-files.txt | uniq >  .etags-el-files.1.txt
-rm -f .etags-el-files.txt
-mv .etags-el-files.1.txt .etags-el-files.txt
-run__etags__el < .etags-el-files.txt
-
-file_count="$(wc -l .etags-el-files.txt | awk '{print $1}')"
-printf "\
-%s - %s files found and processed.
-           Created: %s/TAGS
-           Scanned file list stored in: %s/.etags-el-files.txt
-" "${pgm_name}" "${file_count}" "$(pwd)" "$(pwd)" 1>&2
-
-# -----------------------------------------------------------------------------
+# ----------------------------------------------------------------------------
 # Local Variables:
 # sh-shell: sh
 # End:
diff --git a/bin/etags-erl b/bin/etags-erl
--- a/bin/etags-erl
+++ b/bin/etags-erl
@@ -4,7 +4,7 @@
 #  Purpose   : Build Emacs Tags file for Erlang and C source code files.
 #  Created   : Monday, November  9 2020.
 #  Author    : Pierre Rouleau <prouleau001@gmail.com>
-#  Time-stamp: <2025-04-25 09:26:03 EDT, updated by Pierre Rouleau>
+#  Time-stamp: <2025-04-25 13:49:56 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 #  Module Description
 #  ------------------
@@ -44,10 +44,12 @@
 #      "sys\.config\.src"
 
 # ----------------------------------------------------------------------------
-#  Code
-#  ----
+# Code
+# ----
 
 pgm_name="$(basename "$0")"
+etags_flist_fname=.etags-erl-files.txt
+etags_flist_envvar_fname="$ETAGS_FILE_LIST_FOR_ERLANG"
 
 print_usage()
 {
@@ -60,7 +62,8 @@ print_usage()
 
   • Print this help information.
 
- Usage: %s [DIRPATH ...]
+ Usage: %s [-u] [DIRPATH ...]
+        %s [-u] [--list=FILENAME]
 
   • [Re]build an etags-compliant TAGS file in current directory
     for the Erlang and C files found:
@@ -71,7 +74,8 @@ print_usage()
   • Inspects content of .erl, .hrl, .c, .h, app and rebar files.
   • Stores the names of inspected files in the file named
    .etags-erl-files.txt stored in the same directory as TAGS.
-  • Uses etags to build the TAGS file by default.
+  • Uses etags to build the TAGS file by default, but
+   • -u : force use Universal Ctags (ctags) instead of etags.
    • Set ETAGS_USE_UCTAGS to 1 or to the absolute path of Universal
      Ctags executable file to force using Universal Ctags instead.
      When setting it to 1, the ctags found in PATH is expected
@@ -90,7 +94,7 @@ print_usage()
   • The only output on stdout is the list of files found.
     This allows this script to be used as the first in a pipe
     to do other processing with the list of files found.
-" "$pgm_name" "$pgm_name" "$pgm_name"
+" "$pgm_name" "$pgm_name" "$pgm_name" "$pgm_name"
     if [ "$ETAGS_USE_FIND" = "1" ]; then
         printf -- "
 ⚠️   ETAGS_USE_FIND is currently set to 1, forcing the use of 'find'!
@@ -102,8 +106,18 @@ print_usage()
 }
 
 # --
+# run__etags__erl_c -- run etags or ctags on a set of files
+# -----------------
+#
+# Use etags to parse the source code files unless ETAGS_USE_UCTAGS
+# environment variable is set to 1.  In which case it uses ctags.
+# Ideally that would be the latest version of Universal ctags
+# from https://github.com/universal-ctags/ctags#readme as opposed to the
+# old and currently un-maintained Exeburant ctags.
+# When using Emacs, Emacs provides its own ctags that is essentially etags.
+# Etags generates a tag file format a little different and better suited for Emacs.
 
-run__etags_erl_c()
+run__etags__erl_c()
 {
     # Expects no argument, but expects a list of files to parse on stdin.
 
@@ -115,8 +129,8 @@ run__etags_erl_c()
             xargs "$ETAGS_USE_UCTAGS" --output-format=etags
             printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n"  "$ETAGS_USE_UCTAGS" 1>&2
         else
-            printf -- "*** ERROR: %s: invalid ETAGS_USE_UCTAGS value\n" "$pgm_name" 1>&2
-            printf -- "***  ETAGS_USE_UCTAGS : %s\n" "$ETAGS_USE_UCTAGS"       1>&2
+            printf -- "*** ERROR: %s: invalid ETAGS_USE_UCTAGS value\n" "${pgm_name}" 1>&2
+            printf -- "***  ETAGS_USE_UCTAGS : %s\n" "$ETAGS_USE_UCTAGS" 1>&2
             printf -- "***  This is not 1 nor a valid executable file name.\n" 1>&2
             exit 4
         fi
@@ -131,50 +145,45 @@ run__etags_erl_c()
 if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
     print_usage
     if [ "$#" = "1" ]; then
+        # help requested explicitly with right amount of args: no error.
         exit 0
     else
         exit  1
     fi
 fi
 
-# --
-# Check the validity of directory names specified as arguments.
-# Ensure that each directory specified on the command line
-# exists.  Also ensure that a directory name is not specified more
-# than once.  Use the realpath of that directory name when comparing.
-
-dpaths=
-for dname in "$@"; do
-    if [ ! -d "${dname}" ]; then
-        printf -- "Specified directory does not exists: %s\n" "${dname}" 1>&2
-        exit 2
+# Check -u option to force use of universal ctags
+if [ "$1" = "-u" ]; then
+    if [ -z "$ETAGS_USE_UCTAGS" ]; then
+        printf -- "%s: -u option requests use of Universal Ctags.\n" "${pgm_name}" 1>&2
+        ETAGS_USE_UCTAGS=1
+    else
+        printf -- "%s: -u option not necessary (but does no harm).\n" "${pgm_name}" 1>&2
+        printf -- " ETAGS_USE_UCTAGS is already set to: %s\n" "$ETAGS_USE_UCTAGS" 1>&2
     fi
-    dpath="$(realpath "${dname}")"
-    for dp in ${dpaths}; do
-        if [ "$dp" = "$dpath" ]; then
-            printf -- "Multiple entry of directory: %s\n" "${dname}" 1>&2
-            exit 3
-        fi
-        # check if new entry is a sub-directory of an exiting entry
-        case "${dpath}" in
-            "${dp}/"*)
-                printf -- "%s is a sub-dir of already specified %s\n" "${dname}" "${dp}" 1>&2
-                exit 3
-                ;;
-        esac
-        # check if new entry is a parent directory of an existing entry
-        case "${dp}" in
-            "${dpath}/"*)
-                printf -- "%s is a parent dir of already specified %s\n" "${dname}" "${dp}" 1>&2
-                exit 3
-                ;;
-        esac
-    done
-    dpaths="${dpaths} ${dpath}"
-done
+    shift
+fi
 
 # --
+#  Check --list option to extract list of Erlang files.
 
+case "$1" in
+    --list=*)
+    # extract the file name from the --list= option
+        fname="$(echo "$1" | sed 's/--list=//g')"
+        if [ ! -f "${fname}" ]; then
+            printf -- "\
+*** ERROR: %s: specified list file does not exist: %s
+" "${pgm_name}" "${fname}" 1>&2
+            exit 1
+        else
+            etags_flist_envvar_fname="${fname}"
+            shift
+        fi
+        ;;
+esac
+
+# ----------------------------------------------------------------------------
 # Define a function that searches into 1 directory
 # and accumulates the list of found files into the
 # file '.etags-erl-files.txt'.
@@ -198,13 +207,14 @@ search_with_find()
     # Arg: dirname : name of directory tree to search
 
     # Search for C and Erlang files
-    find -L ${find_path_option} "$dirname" -name "*.[ch]" \
-         -print | tee -a .etags-erl-files.txt
-    find -L -f "$dirname" \
-         \(  -name "*\.[he]rl" \
-         -or -name "*\.app" \
-         -or -name "*\.app.src" \) \
-         -print | tee -a .etags-erl-files.txt
+    find -L ${find_path_option} "$dirname" \
+         \( -name "*.[ch]"                 \
+         \) -print | tee -a "${etags_flist_fname}"
+    find -L -f "$dirname"          \
+         \(  -name "*\.[he]rl"     \
+         -or -name "*\.app"        \
+         -or -name "*\.app.src"    \
+         \) -print | tee -a "${etags_flist_fname}"
 }
 
 search_with_fd()
@@ -214,12 +224,12 @@ search_with_fd()
 
     # Search for C and Erlang files
     ${fd_pgm} -L --type f -e .c  -e .h \
-           '' "$dirname" | tee -a .etags-erl-files.txt
+           '' "$dirname" | tee -a "${etags_flist_fname}"
     ${fd_pgm} -L --type f \
            -e .erl  -e .hrl \
            -e .app \
            -e .app.src \
-           '' "$dirname" | tee -a .etags-erl-files.txt
+           '' "$dirname" | tee -a "${etags_flist_fname}"
 }
 
 search()
@@ -237,65 +247,148 @@ search()
     esac
 }
 
-# --
-# First prepare environment
-# Select the method to search for files.
-# - Try to use fd or fdfind if they exist,
-#   otherwise use find.
-# - Echo the actual program used to find files (on stderr).
-if [ "$ETAGS_USE_FIND" = "1" ]; then
-    search_with='find'
-    echo "- ETAGS_USE_FIND forces the use of find!" 1>&2
-    echo "-> Using" "$(which find)"                 1>&2
-else
-    if [ -x "$(command -v fdfind)" ]; then
-        search_with='fd'
-        fd_pgm=fdfind
-        echo "-> Using" "$(which fdfind)"  1>&2
-        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
+use_rg="false"
+if [ -x "$(command -v rg)" ]; then
+    use_rg="true"
+fi
 
-    elif [ -x "$(command -v fd)" ]; then
-        search_with='fd'
-        fd_pgm=fd
-        echo "-> Using" "$(which fd)" 1>&2
-        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
+search_script()
+{
+    # Arg: dirname : name of directory tree to search
+    # add shell scripts that use Perl. Exclude perltidy files, Emacs backup and buffers files
+    if [ "${dirname}" = "." ]; then
+        real_dname=.
     else
-        search_with='find'
-        echo "-> Using" "$(which find)" 1>&2
+        real_dname="$(realpath "$dname")"
     fi
-fi
 
-# -- proceed
-# remove the old list of files.
-rm -f .etags-erl-files.txt
+    # Find extension-less erlang escript script files in specified directory
+    if [ "$use_rg" = "true" ]; then
+        rg  -g !'*~' -g !'*#' -Nl "^#!.* escript" "${real_dname}" | tee -a "${etags_flist_fname}"
+    else
+        grep --exclude '*~' --exclude '*#' -E -r "^#!.* escript" "${real_dname}" | tee -a "${etags_flist_fname}"
+    fi
+}
 
-# Search in all specified directory to build the list of
-# files in the file '.etags-erl-files.txt'.
+# --
+# Proceed
 
-printf -- "%s - Processing %s/ ...\n" "${pgm_name}" "$(pwd)" 1>&2
-
-if [ -z "$1" ]; then
-    dirname="."
-    search
+if [ -n "${etags_flist_envvar_fname}" ]; then
+    if [ "${etags_flist_envvar_fname}" = "${etags_flist_fname}" ]; then
+        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_ERLANG to %s\n" "${pgm_name}" "${etags_flist_fname}"1>&2
+        exit 1
+    fi
+    printf -- "Using the file list identified by ETAGS_FILE_LIST_FOR_ERLANG: %s\n" "${etags_flist_envvar_fname}" 1>&2
+    cp "${etags_flist_envvar_fname}" "${etags_flist_fname}"
+    run__etags__erl_c < "${etags_flist_envvar_fname}"
 else
-    for dirname in "$@"; do
-        search
+    # Check the validity of directory names specified as arguments.
+    # Ensure that each directory specified on the command line
+    # exists.  Also ensure that a directory name is not specified more
+    # than once.  Use the realpath of that directory name when comparing.
+    # Exit on the first error detected.
+    dpaths=
+    for dname in "$@"; do
+        if [ ! -d "${dname}" ]; then
+            printf -- "Specified directory does not exists: %s\n" "${dname}" 1>&2
+            exit 2
+        fi
+        dpath="$(realpath "${dname}")"
+        for dp in ${dpaths}; do
+            if [ "$dp" = "$dpath" ]; then
+                printf -- "Multiple entry of directory: %s\n" "${dname}" 1>&2
+                exit 3
+            fi
+            # check if new entry is a sub-directory of an exiting entry
+            case "${dpath}" in
+                "${dp}/"*)
+                    printf -- "%s is a sub-dir of already specified %s\n" "${dname}" "${dp}" 1>&2
+                    exit 3
+                    ;;
+            esac
+            # check if new entry is a parent directory of an existing entry
+            case "${dp}" in
+                "${dpath}/"*)
+                    printf -- "%s is a parent dir of already specified %s\n" "${dname}" "${dp}" 1>&2
+                    exit 3
+                    ;;
+            esac
+        done
+        dpaths="${dpaths} ${dpath}"
     done
+
+    # --
+    # First prepare environment
+    # Select the method to search for files.
+    # - Try to use fd or fdfind if they exist,
+    #   otherwise use find.
+    # - Echo the actual program used to find files (on stderr).
+    if [ "$ETAGS_USE_FIND" = "1" ]; then
+        search_with='find'
+        echo "- ETAGS_USE_FIND forces the use of find!" 1>&2
+        echo "-> Using" "$(which find)"                 1>&2
+    else
+        if [ -x "$(command -v fdfind)" ]; then
+            search_with='fd'
+            fd_pgm=fdfind
+            echo "-> Using" "$(which fdfind)" 1>&2
+            echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
+        elif [ -x "$(command -v fd)" ]; then
+            search_with='fd'
+            fd_pgm=fd
+            echo "-> Using" "$(which fd)" 1>&2
+            echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
+        else
+            search_with='find'
+            echo "-> Using" "$(which find)" 1>&2
+        fi
+    fi
+
+    printf -- "No list of files identified by ETAGS_FILE_LIST_FOR_ERLANG.\n" 1>&2
+    printf -- "Files found printed in found order (not necessarily in sorted order)\n" 1>&2
+
+    # -- proceed
+    # Rename the old list of files if it exists
+    if [ -e "${etags_flist_fname}" ]; then
+        mv "${etags_flist_fname}" "${etags_flist_fname}.backup"
+    fi
+
+    # Search in all specified directory to build the list of
+    # files in the file '.etags-erl-files.txt'.
+    if [ -z "$1" ]; then
+        dirname="."
+        search
+        search_script
+    else
+        for dirname in "$@"; do
+            search
+            search_script
+        done
+    fi
+
+    # Then run etags on these files, and sort them in the etags file
+    sort < "${etags_flist_fname}" | uniq >  "${etags_flist_fname}.new"
+    rm -f "${etags_flist_fname}"
+    mv "${etags_flist_fname}.new" "${etags_flist_fname}"
+    run__etags__rust < "${etags_flist_fname}"
 fi
 
-
-# Then run etags on these files, and sort them in the etags file
-sort < .etags-erl-files.txt | uniq >  .etags-erl-files.1.txt
-rm -f .etags-erl-files.txt
-mv .etags-erl-files.1.txt .etags-erl-files.txt
-run__etags__make < .etags-erl-files.txt
-
-file_count="$(wc -l .etags-erl-files.txt | awk '{print $1}')"
-printf "\
-%s - %s files found and processed.
-           Created: %s/TAGS
-           Scanned file list stored in: %s/.etags-erl-files.txt
-" "${pgm_name}" "${file_count}" "$(pwd)" "$(pwd)" 1>&2
+file_count="$(wc -l "${etags_flist_fname}" | awk '{print $1}')"
+if [ "$file_count" = "0" ]; then
+    # restore the old list of files.
+    rm -rf "${etags_flist_fname}"
+    if [ -e "${etags_flist_fname}.backup" ]; then
+        mv "${etags_flist_fname}.backup"  "${etags_flist_fname}"
+    fi
+    printf -- "No files found. %s and TAGS files untouched.\n" "${etags_flist_fname}"  1>&2
+    exit 1
+else
+  rm -rf "${etags_flist_fname}.backup"
+  printf "\
+  %s - %s files found and processed.
+             Created: %s/TAGS
+             Scanned file list stored in: %s/%s\n" "${pgm_name}" "${file_count}" "$(pwd)" "$(pwd)" "${etags_flist_fname}" 1>&2
+fi
 
 # ----------------------------------------------------------------------------
 # Local Variables:
diff --git a/bin/etags-lisp b/bin/etags-lisp
--- a/bin/etags-lisp
+++ b/bin/etags-lisp
@@ -4,7 +4,7 @@
 #  Purpose   : Build Emacs Tags file for Lisp source code files.
 #  Created   : Tuesday, November 10 2020.
 #  Author    : Pierre Rouleau <prouleau001@gmail.com>
-#  Time-stamp: <2025-04-25 09:26:34 EDT, updated by Pierre Rouleau>
+#  Time-stamp: <2025-04-25 15:04:52 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 #  Module Description
 #  ------------------
@@ -34,6 +34,8 @@
 #  ----
 
 pgm_name="$(basename "$0")"
+etags_flist_fname=.etags-lisp-files.txt
+etags_flist_envvar_fname="$ETAGS_FILE_LIST_FOR_LISP"
 
 print_usage()
 {
@@ -47,11 +49,14 @@ print_usage()
   • Print this help information.
 
  Usage: %s [DIRPATH ...]
+        %s [--list=FILENAME]
 
   • [Re]build an etags-compliant TAGS file in current directory
     for the Common Lisp files found:
     - in the DIRPATH directory tree(s) identified on the command line, or
-      the current directory if none is specified.
+      the current directory if none is specified, or
+    - in the list provided in the FILENAME specified by the --list option, or
+    - specified by the ETAGS_FILE_LIST_FOR_LISP environment variable.
   • Follows symbolic links both for directories and files.
   • Overwrites any TAGS file in the current directory.
   • Inspects content of .cl, .clisp, .l, .lisp, .LSP, .lsp and .ml
@@ -74,7 +79,7 @@ print_usage()
   • The only output on stdout is the list of files found.
     This allows this script to be used as the first in a pipe
     to do other processing with the list of files found.
-" "$pgm_name" "$pgm_name" "$pgm_name"
+" "$pgm_name" "$pgm_name" "$pgm_name" "$pgm_name"
     if [ "$ETAGS_USE_FIND" = "1" ]; then
         printf -- "
 ⚠️   ETAGS_USE_FIND is currently set to 1, forcing the use of 'find'!
@@ -86,8 +91,14 @@ print_usage()
 }
 
 # --
+# run__etags__lisp -- run etags on a set of files
+# --------------
+#
+# Use etags to parse the source code files.
+# Don't use ctags because it does not support compressed files.
+# Etags generates a tag file format a little different and better suited for Emacs.
 
-run__etags_lisp()
+run__etags__lisp()
 {
     # Expects no argument, but expects a list of files to parse on stdin.
 
@@ -103,6 +114,7 @@ run__etags_lisp()
 if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
     print_usage
     if [ "$#" = "1" ]; then
+        # help requested explicitly with right amount of args: no error.
         exit 0
     else
         exit  1
@@ -110,43 +122,25 @@ if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
 fi
 
 # --
-# Check the validity of directory names specified as arguments.
-# Ensure that each directory specified on the command line
-# exists.  Also ensure that a directory name is not specified more
-# than once.  Use the realpath of that directory name when comparing.
+#  Check --list option to extract list of Lisp files.
 
-dpaths=
-for dname in "$@"; do
-    if [ ! -d "${dname}" ]; then
-        printf -- "Specified directory does not exists: %s\n" "${dname}" 1>&2
-        exit 2
-    fi
-    dpath="$(realpath "${dname}")"
-    for dp in ${dpaths}; do
-        if [ "$dp" = "$dpath" ]; then
-            printf -- "Multiple entry of directory: %s\n" "${dname}" 1>&2
-            exit 3
+case "$1" in
+    --list=*)
+    # extract the file name from the --list= option
+        fname="$(echo "$1" | sed 's/--list=//g')"
+        if [ ! -f "${fname}" ]; then
+            printf -- "\
+*** ERROR: %s: specified list file does not exist: %s
+" "${pgm_name}" "${fname}" 1>&2
+            exit 1
+        else
+            etags_flist_envvar_fname="${fname}"
+            shift
         fi
-        # check if new entry is a sub-directory of an exiting entry
-        case "${dpath}" in
-            "${dp}/"*)
-                printf -- "%s is a sub-dir of already specified %s\n" "${dname}" "${dp}" 1>&2
-                exit 3
-                ;;
-        esac
-        # check if new entry is a parent directory of an existing entry
-        case "${dp}" in
-            "${dpath}/"*)
-                printf -- "%s is a parent dir of already specified %s\n" "${dname}" "${dp}" 1>&2
-                exit 3
-                ;;
-        esac
-    done
-    dpaths="${dpaths} ${dpath}"
-done
+        ;;
+esac
 
-# --
-
+# ----------------------------------------------------------------------------
 # Define a function that searches into 1 directory
 # and accumulates the list of found files into the
 # file '.etags-lisp-files.txt'.
@@ -165,18 +159,22 @@ case $(uname) in
         ;;
 esac
 
+# [:todo 2025-04-25, by Pierre Rouleau: Check extensions: are .ml really used for Common Lisp?
+#                                        They are used for OCaml...
+#                                        Also may want to check for .fasl files.]
 search_with_find()
 {
     # Arg: dirname : name of directory tree to search
 
-    find -L ${find_path_option} "$dirname" \( -name "*.cl"    -or -name "*.cl.gz" \
+    find -L ${find_path_option} "$dirname"          \
+         \(  -name "*.cl"    -or -name "*.cl.gz"    \
          -or -name "*.clisp" -or -name "*.clisp.gz" \
-         -or -name "*.l"     -or -name "*.l.gz"    \
-         -or -name "*.lisp"  -or -name "*.lisp.gz" \
-         -or -name "*.LSP"   -or -name "*.LSP.gz" \
-         -or -name "*.lsp"   -or -name "*.lsp.gz" \
-         -or -name "*.ml"    -or -name "*.ml.gz" \
-         \)  -print | tee -a .etags-lisp-files.txt
+         -or -name "*.l"     -or -name "*.l.gz"     \
+         -or -name "*.lisp"  -or -name "*.lisp.gz"  \
+         -or -name "*.LSP"   -or -name "*.LSP.gz"   \
+         -or -name "*.lsp"   -or -name "*.lsp.gz"   \
+         -or -name "*.ml"    -or -name "*.ml.gz"    \
+         \)  -print | tee -a "${etags_flist_fname}"
 }
 
 search_with_fd()
@@ -184,15 +182,15 @@ search_with_fd()
     # Arg: dirname : name of directory tree to search
     # Arg: fd_pgm  : fd or fdfind
 
-    ${fd_pgm} -L --type f \
-              -e .cl    -e .cl.gz \
-              -e .clisp -e .clisp.gz \
-              -e .l     -e .l.gz \
-              -e .lisp  -e .lisp.gz \
-              -e .LSP   -e .LSP.gz \
-              -e .lsp   -e .lsp.gz \
-              -e .ml    -e .ml.gz \
-              '' "$dirname" | tee -a .etags-lisp-files.txt
+    ${fd_pgm} -L --type f             \
+              -e .cl    -e .cl.gz     \
+              -e .clisp -e .clisp.gz  \
+              -e .l     -e .l.gz      \
+              -e .lisp  -e .lisp.gz   \
+              -e .LSP   -e .LSP.gz    \
+              -e .lsp   -e .lsp.gz    \
+              -e .ml    -e .ml.gz     \
+              '' "$dirname" | tee -a "${etags_flist_fname}"
 }
 
 search()
@@ -211,66 +209,124 @@ search()
 }
 
 # --
-# First prepare environment
-# Select the method to search for files.
-# - Try to use fd or fdfind if they exist,
-#   otherwise use find.
-# - Echo the actual program used to find files (on stderr).
-if [ "$ETAGS_USE_FIND" = "1" ]; then
-    search_with='find'
-    echo "- ETAGS_USE_FIND forces the use of find!" 1>&2
-    echo "-> Using" "$(which find)"                 1>&2
-else
-    if [ -x "$(command -v fdfind)" ]; then
-        search_with='fd'
-        fd_pgm=fdfind
-        echo "-> Using" "$(which fdfind)"  1>&2
-        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
+# Proceed
 
-    elif [ -x "$(command -v fd)" ]; then
-        search_with='fd'
-        fd_pgm=fd
-        echo "-> Using" "$(which fd)" 1>&2
-        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
-    else
-        search_with='find'
-        echo "-> Using" "$(which find)" 1>&2
+if [ -n "${etags_flist_envvar_fname}" ]; then
+    if [ "${etags_flist_envvar_fname}" = "${etags_flist_fname}" ]; then
+        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_LISP to %s\n" "${pgm_name}" "${etags_flist_fname}"1>&2
+        exit 1
     fi
-fi
-
-# -- proceed
-# remove the old list of files.
-rm -f .etags-lisp-files.txt
-
-# Search in all specified directory to build the list of
-# files in the file '.etags-lisp-files.txt'.
-
-printf -- "%s - Processing %s/ ...\n" "${pgm_name}" "$(pwd)" 1>&2
-
-if [ -z "$1" ]; then
-    dirname="."
-    search
+    printf -- "Using the file list identified by ETAGS_FILE_LIST_FOR_LISP: %s\n" "${etags_flist_envvar_fname}" 1>&2
+    cp "${etags_flist_envvar_fname}" "${etags_flist_fname}"
+    run__etags__lisp < "${etags_flist_envvar_fname}"
 else
-    for dirname in "$@"; do
-        search
+    # Check the validity of directory names specified as arguments.
+    # Ensure that each directory specified on the command line
+    # exists.  Also ensure that a directory name is not specified more
+    # than once.  Use the realpath of that directory name when comparing.
+    # Exit on the first error detected.
+    dpaths=
+    for dname in "$@"; do
+        if [ ! -d "${dname}" ]; then
+            printf -- "Specified directory does not exists: %s\n" "${dname}" 1>&2
+            exit 2
+        fi
+        dpath="$(realpath "${dname}")"
+        for dp in ${dpaths}; do
+            if [ "$dp" = "$dpath" ]; then
+                printf -- "Multiple entry of directory: %s\n" "${dname}" 1>&2
+                exit 3
+            fi
+            # check if new entry is a sub-directory of an exiting entry
+            case "${dpath}" in
+                "${dp}/"*)
+                    printf -- "%s is a sub-dir of already specified %s\n" "${dname}" "${dp}" 1>&2
+                    exit 3
+                    ;;
+            esac
+            # check if new entry is a parent directory of an existing entry
+            case "${dp}" in
+                "${dpath}/"*)
+                    printf -- "%s is a parent dir of already specified %s\n" "${dname}" "${dp}" 1>&2
+                    exit 3
+                    ;;
+            esac
+        done
+        dpaths="${dpaths} ${dpath}"
     done
+
+    # --
+    # First prepare environment
+    # Select the method to search for files.
+    # - Try to use fd or fdfind if they exist,
+    #   otherwise use find.
+    # - Echo the actual program used to find files (on stderr).
+    if [ "$ETAGS_USE_FIND" = "1" ]; then
+        search_with='find'
+        echo "- ETAGS_USE_FIND forces the use of find!" 1>&2
+        echo "-> Using" "$(which find)"                 1>&2
+    else
+        if [ -x "$(command -v fdfind)" ]; then
+            search_with='fd'
+            fd_pgm=fdfind
+            echo "-> Using" "$(which fdfind)" 1>&2
+            echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
+        elif [ -x "$(command -v fd)" ]; then
+            search_with='fd'
+            fd_pgm=fd
+            echo "-> Using" "$(which fd)" 1>&2
+            echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
+        else
+            search_with='find'
+            echo "-> Using" "$(which find)" 1>&2
+        fi
+    fi
+
+    printf -- "No list of files identified by ETAGS_FILE_LIST_FOR_LISP.\n" 1>&2
+    printf -- "Files found printed in found order (not necessarily in sorted order)\n" 1>&2
+
+    # -- proceed
+    # Rename the old list of files if it exists
+    if [ -e "${etags_flist_fname}" ]; then
+        mv "${etags_flist_fname}" "${etags_flist_fname}.backup"
+    fi
+
+    # Search in all specified directory to build the list of
+    # files in the file '.etags-lisp-files.txt'.
+    if [ -z "$1" ]; then
+        dirname="."
+        search
+    else
+        for dirname in "$@"; do
+            search
+        done
+    fi
+
+    # Then run etags on these files, and sort them in the etags file
+    sort < "${etags_flist_fname}" | uniq >  "${etags_flist_fname}.new"
+    rm -f "${etags_flist_fname}"
+    mv "${etags_flist_fname}.new" "${etags_flist_fname}"
+    run__etags__lisp < "${etags_flist_fname}"
 fi
 
+file_count="$(wc -l "${etags_flist_fname}" | awk '{print $1}')"
+if [ "$file_count" = "0" ]; then
+    # restore the old list of files.
+    rm -rf "${etags_flist_fname}"
+    if [ -e "${etags_flist_fname}.backup" ]; then
+        mv "${etags_flist_fname}.backup"  "${etags_flist_fname}"
+    fi
+    printf -- "No files found. %s and TAGS files untouched.\n" "${etags_flist_fname}"  1>&2
+    exit 1
+else
+  rm -rf "${etags_flist_fname}.backup"
+  printf "\
+  %s - %s files found and processed.
+             Created: %s/TAGS
+             Scanned file list stored in: %s/%s\n" "${pgm_name}" "${file_count}" "$(pwd)" "$(pwd)" "${etags_flist_fname}" 1>&2
+fi
 
-# Then run etags on these files, and sort them in the etags file
-sort < .etags-lisp-files.txt | uniq >  .etags-lisp-files.1.txt
-rm -f .etags-lisp-files.txt
-mv .etags-lisp-files.1.txt .etags-lisp-files.txt
-run__etags_lisp < .etags-lisp-files.txt
-
-file_count="$(wc -l .etags-lisp-files.txt | awk '{print $1}')"
-printf "\
-%s - %s files found and processed.
-           Created: %s/TAGS
-           Scanned file list stored in: %s/.etags-lisp-files.txt
-" "${pgm_name}" "${file_count}" "$(pwd)" "$(pwd)" 1>&2
-
-# -----------------------------------------------------------------------------
+# ----------------------------------------------------------------------------
 # Local Variables:
 # sh-shell: sh
 # End:
diff --git a/bin/etags-make b/bin/etags-make
--- a/bin/etags-make
+++ b/bin/etags-make
@@ -4,7 +4,7 @@
 #  Purpose   : Build Emacs Tags file for Make source code files.
 #  Created   : Thursday, June 6, 2024
 #  Author    : Pierre Rouleau <prouleau001@gmail.com>
-#  Time-stamp: <2025-04-25 09:26:50 EDT, updated by Pierre Rouleau>
+#  Time-stamp: <2025-04-25 15:24:04 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 #  Module Description
 #  ------------------
@@ -40,6 +40,8 @@
 #  ----
 
 pgm_name="$(basename "$0")"
+etags_flist_fname=.etags-make-files.txt
+etags_flist_envvar_fname="$ETAGS_FILE_LIST_FOR_MAKE"
 
 print_usage()
 {
@@ -53,11 +55,14 @@ print_usage()
   • Print this help information.
 
  Usage: %s [-u] [DIRPATH ...]
+        %s [-u] [--list=FILENAME]
 
   • [Re]build an etags-compliant TAGS file in current directory
     for the GNU Make source code files found:
     - in the DIRPATH directory tree(s) identified on the command line, or
-      the current directory if none is specified.
+      the current directory if none is specified, or
+    - in the list provided in the FILENAME specified by the --list option, or
+    - specified by the ETAGS_FILE_LIST_FOR_MAKE environment variable.
   • Follows symbolic links both for directories and files.
   • Uses etags to build the TAGS file by default, but
     -u : force use Universal Ctags (ctags) instead of etags.
@@ -77,10 +82,14 @@ print_usage()
     variable to 1.
   • ☝️  When 'fdfind' or 'fd' is used, the content of files identified
     by the .gitignore, .ignore or .fdignore files are ignored.
-  • The only output on stdout is the list of files found.
+  • Info printed on stderr:
+   • The path of the find program used and when repository ignore files
+     are skipped from the scan.
+   • A count of found files, and the name of the file that holds them.
+ • The only output on stdout is the list of files found.
     This allows this script to be used as the first in a pipe
     to do other processing with the list of files found.
-" "$pgm_name" "$pgm_name" "$pgm_name"
+" "$pgm_name" "$pgm_name" "$pgm_name" "$pgm_name"
     if [ "$ETAGS_USE_FIND" = "1" ]; then
         printf -- "
 ⚠️   ETAGS_USE_FIND is currently set to 1, forcing the use of 'find'!
@@ -92,6 +101,16 @@ print_usage()
 }
 
 # --
+# run__etags__make -- run etags or ctags on a set of files
+# ----------------
+#
+# Use etags to parse the source code files unless ETAGS_USE_UCTAGS
+# environment variable is set to 1.  In which case it uses ctags.
+# Ideally that would be the latest version of Universal ctags
+# from https://github.com/universal-ctags/ctags#readme as opposed to the
+# old and currently un-maintained Exeburant ctags.
+# When using Emacs, Emacs provides its own ctags that is essentially etags.
+# Etags generates a tag file format a little different and better suited for Emacs.
 
 run__etags__make()
 {
@@ -100,12 +119,12 @@ run__etags__make()
     if [ -n "$ETAGS_USE_UCTAGS" ]; then
         if [ "$ETAGS_USE_UCTAGS" = "1" ]; then
             xargs ctags --output-format=etags
-            printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n"  "$(which ctags)" 1>&2
+            printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n" "$(which ctags)" 1>&2
         elif [ -x "$ETAGS_USE_UCTAGS" ]; then
             xargs "$ETAGS_USE_UCTAGS" --output-format=etags
-            printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n"  "$ETAGS_USE_UCTAGS" 1>&2
+            printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n" "$ETAGS_USE_UCTAGS" 1>&2
         else
-            printf -- "*** ERROR: %s : invalid ETAGS_USE_UCTAGS value\n" "${pgm_name}" 1>&2
+            printf -- "*** ERROR: %s: invalid ETAGS_USE_UCTAGS value\n" "${pgm_name}" 1>&2
             printf -- "***  ETAGS_USE_UCTAGS : %s\n" "$ETAGS_USE_UCTAGS" 1>&2
             printf -- "***  This is not 1 nor a valid executable file name.\n" 1>&2
             exit 4
@@ -121,6 +140,7 @@ run__etags__make()
 if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
     print_usage
     if [ "$#" = "1" ]; then
+        # help requested explicitly with right amount of args: no error.
         exit 0
     else
         exit  1
@@ -134,49 +154,31 @@ if [ "$1" = "-u" ]; then
         ETAGS_USE_UCTAGS=1
     else
         printf -- "%s: -u option not necessary (but does no harm).\n" "${pgm_name}" 1>&2
-        printf -- " ETAGS_USE_UCTAGS is already set to: %s\n" "$ETAGS_USE_UCTAGS"  1>&2
+        printf -- " ETAGS_USE_UCTAGS is already set to: %s\n" "$ETAGS_USE_UCTAGS" 1>&2
     fi
     shift
 fi
 
 # --
-# Check the validity of directory names specified as arguments.
-# Ensure that each directory specified on the command line
-# exists.  Also ensure that a directory name is not specified more
-# than once.  Use the realpath of that directory name when comparing.
+#  Check --list option to extract list of make files.
 
-dpaths=
-for dname in "$@"; do
-    if [ ! -d "${dname}" ]; then
-        printf -- "Specified directory does not exists: %s\n" "${dname}" 1>&2
-        exit 2
-    fi
-    dpath="$(realpath "${dname}")"
-    for dp in ${dpaths}; do
-        if [ "$dp" = "$dpath" ]; then
-            printf -- "Multiple entry of directory: %s\n" "${dname}" 1>&2
-            exit 3
+case "$1" in
+    --list=*)
+    # extract the file name from the --list= option
+        fname="$(echo "$1" | sed 's/--list=//g')"
+        if [ ! -f "${fname}" ]; then
+            printf -- "\
+*** ERROR: %s: specified list file does not exist: %s
+" "${pgm_name}" "${fname}" 1>&2
+            exit 1
+        else
+            etags_flist_envvar_fname="${fname}"
+            shift
         fi
-        # check if new entry is a sub-directory of an exiting entry
-        case "${dpath}" in
-            "${dp}/"*)
-                printf -- "%s is a sub-dir of already specified %s\n" "${dname}" "${dp}" 1>&2
-                exit 3
-                ;;
-        esac
-        # check if new entry is a parent directory of an existing entry
-        case "${dp}" in
-            "${dpath}/"*)
-                printf -- "%s is a parent dir of already specified %s\n" "${dname}" "${dp}" 1>&2
-                exit 3
-                ;;
-        esac
-    done
-    dpaths="${dpaths} ${dpath}"
-done
+        ;;
+esac
 
-# --
-
+# ----------------------------------------------------------------------------
 # Define a function that searches into 1 directory
 # and accumulates the list of found files into the
 # file '.etags-make-files.txt'.
@@ -195,20 +197,19 @@ case $(uname) in
         ;;
 esac
 
-
 search_with_find()
 {
     # Arg: dirname : name of directory tree to search
 
-    find -L ${find_path_option} "$dirname" \( \
-         -name     "Makefile" \
-         -or -name "makefile" \
-         -or -name "GNUMakefile" \
-         -or -name "Makefile.in" \
-         -or -name "Makefile.am" \
-         -or -name "*\.mk" \
-         -or -name "*\.mak" \
-         \)  -print | tee -a .etags-make-files.txt
+    find -L ${find_path_option} "$dirname" \
+         \(  -name "Makefile"              \
+         -or -name "makefile"              \
+         -or -name "GNUMakefile"           \
+         -or -name "Makefile.in"           \
+         -or -name "Makefile.am"           \
+         -or -name "*\.mk"                 \
+         -or -name "*\.mak"                \
+         \)  -print | tee -a "${etags_flist_fname}"
 }
 
 search_with_fd()
@@ -216,11 +217,13 @@ search_with_fd()
     # Arg: dirname : name of directory tree to search
     # Arg: fd_pgm  : fd or fdfind
 
+    # Note: fd expects a regexp-string.  Use '' if none is required, otherwise
+    #       it will take the directory name as a regexp...
     ${fd_pgm} -L --type f '((makefile)|((GNU)?Makefile(.((in)|(am)))?))$' \
-           "$dirname" | tee -a .etags-make-files.txt
+           "$dirname" | tee -a "${etags_flist_fname}"
     # Then the .mk and .mak make files
     ${fd_pgm} -L --type f -e .mk -e .mak\
-           '' "$dirname" | tee -a .etags-make-files.txt
+           '' "$dirname" | tee -a "${etags_flist_fname}"
 }
 
 search()
@@ -239,66 +242,124 @@ search()
 }
 
 # --
-# First prepare environment
-# Select the method to search for files.
-# - Try to use fd or fdfind if they exist,
-#   otherwise use find.
-# - Echo the actual program used to find files (on stderr).
-if [ "$ETAGS_USE_FIND" = "1" ]; then
-    search_with='find'
-    echo "- ETAGS_USE_FIND forces the use of find!" 1>&2
-    echo "-> Using" "$(which find)"                 1>&2
-else
-    if [ -x "$(command -v fdfind)" ]; then
-        search_with='fd'
-        fd_pgm=fdfind
-        echo "-> Using" "$(which fdfind)"  1>&2
-        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
+# Proceed
 
-    elif [ -x "$(command -v fd)" ]; then
-        search_with='fd'
-        fd_pgm=fd
-        echo "-> Using" "$(which fd)" 1>&2
-        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
-    else
-        search_with='find'
-        echo "-> Using" "$(which find)" 1>&2
+if [ -n "${etags_flist_envvar_fname}" ]; then
+    if [ "${etags_flist_envvar_fname}" = "${etags_flist_fname}" ]; then
+        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_MAKE to %s\n" "${pgm_name}" "${etags_flist_fname}"1>&2
+        exit 1
     fi
-fi
-
-# -- proceed
-# remove the old list of files.
-rm -f .etags-make-files.txt
-
-# Search in all specified directory to build the list of
-# files in the file '.etags-make-files.txt'.
-
-printf -- "%s - Processing %s/ ...\n" "${pgm_name}" "$(pwd)" 1>&2
-
-if [ -z "$1" ]; then
-    dirname="."
-    search
+    printf -- "Using the file list identified by ETAGS_FILE_LIST_FOR_MAKE: %s\n" "${etags_flist_envvar_fname}" 1>&2
+    cp "${etags_flist_envvar_fname}" "${etags_flist_fname}"
+    run__etags__make < "${etags_flist_envvar_fname}"
 else
-    for dirname in "$@"; do
-        search
+    # Check the validity of directory names specified as arguments.
+    # Ensure that each directory specified on the command line
+    # exists.  Also ensure that a directory name is not specified more
+    # than once.  Use the realpath of that directory name when comparing.
+    # Exit on the first error detected.
+    dpaths=
+    for dname in "$@"; do
+        if [ ! -d "${dname}" ]; then
+            printf -- "Specified directory does not exists: %s\n" "${dname}" 1>&2
+            exit 2
+        fi
+        dpath="$(realpath "${dname}")"
+        for dp in ${dpaths}; do
+            if [ "$dp" = "$dpath" ]; then
+                printf -- "Multiple entry of directory: %s\n" "${dname}" 1>&2
+                exit 3
+            fi
+            # check if new entry is a sub-directory of an exiting entry
+            case "${dpath}" in
+                "${dp}/"*)
+                    printf -- "%s is a sub-dir of already specified %s\n" "${dname}" "${dp}" 1>&2
+                    exit 3
+                    ;;
+            esac
+            # check if new entry is a parent directory of an existing entry
+            case "${dp}" in
+                "${dpath}/"*)
+                    printf -- "%s is a parent dir of already specified %s\n" "${dname}" "${dp}" 1>&2
+                    exit 3
+                    ;;
+            esac
+        done
+        dpaths="${dpaths} ${dpath}"
     done
+
+    # --
+    # First prepare environment
+    # Select the method to search for files.
+    # - Try to use fd or fdfind if they exist,
+    #   otherwise use find.
+    # - Echo the actual program used to find files (on stderr).
+    if [ "$ETAGS_USE_FIND" = "1" ]; then
+        search_with='find'
+        echo "- ETAGS_USE_FIND forces the use of find!" 1>&2
+        echo "-> Using" "$(which find)"                 1>&2
+    else
+        if [ -x "$(command -v fdfind)" ]; then
+            search_with='fd'
+            fd_pgm=fdfind
+            echo "-> Using" "$(which fdfind)" 1>&2
+            echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
+        elif [ -x "$(command -v fd)" ]; then
+            search_with='fd'
+            fd_pgm=fd
+            echo "-> Using" "$(which fd)" 1>&2
+            echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
+        else
+            search_with='find'
+            echo "-> Using" "$(which find)" 1>&2
+        fi
+    fi
+
+    printf -- "No list of files identified by ETAGS_FILE_LIST_FOR_MAKE.\n" 1>&2
+    printf -- "Files found printed in found order (not necessarily in sorted order)\n" 1>&2
+
+    # -- proceed
+    # Rename the old list of files if it exists
+    if [ -e "${etags_flist_fname}" ]; then
+        mv "${etags_flist_fname}" "${etags_flist_fname}.backup"
+    fi
+
+    # Search in all specified directory to build the list of
+    # files in the file '.etags-make-files.txt'.
+    if [ -z "$1" ]; then
+        dirname="."
+        search
+    else
+        for dirname in "$@"; do
+            search
+        done
+    fi
+
+    # Then run etags on these files, and sort them in the etags file
+    sort < "${etags_flist_fname}" | uniq >  "${etags_flist_fname}.new"
+    rm -f "${etags_flist_fname}"
+    mv "${etags_flist_fname}.new" "${etags_flist_fname}"
+    run__etags__rust < "${etags_flist_fname}"
 fi
 
+file_count="$(wc -l "${etags_flist_fname}" | awk '{print $1}')"
+if [ "$file_count" = "0" ]; then
+    # restore the old list of files.
+    rm -rf "${etags_flist_fname}"
+    if [ -e "${etags_flist_fname}.backup" ]; then
+        mv "${etags_flist_fname}.backup"  "${etags_flist_fname}"
+    fi
+    printf -- "No files found. %s and TAGS files untouched.\n" "${etags_flist_fname}"  1>&2
+    exit 1
+else
+  rm -rf "${etags_flist_fname}.backup"
+  printf "\
+  %s - %s files found and processed.
+             Created: %s/TAGS
+             Scanned file list stored in: %s/%s\n" "${pgm_name}" "${file_count}" "$(pwd)" "$(pwd)" "${etags_flist_fname}" 1>&2
+fi
 
-# Then run etags on these files, and sort them in the etags file
-sort < .etags-make-files.txt | uniq >  .etags-make-files.1.txt
-rm -f .etags-make-files.txt
-mv .etags-make-files.1.txt .etags-make-files.txt
-run__etags__make < .etags-make-files.txt
-
-file_count="$(wc -l .etags-make-files.txt | awk '{print $1}')"
-printf "\
-%s - %s files found and processed.
-           Created: %s/TAGS
-           Scanned file list stored in: %s/.etags-make-files.txt
-" "${pgm_name}" "${file_count}" "$(pwd)" "$(pwd)" 1>&2
-
-# -----------------------------------------------------------------------------
+# ----------------------------------------------------------------------------
 # Local Variables:
 # sh-shell: sh
 # End:
diff --git a/bin/etags-py b/bin/etags-py
--- a/bin/etags-py
+++ b/bin/etags-py
@@ -4,14 +4,14 @@
 #  Purpose   : Build Emacs Tags file for Python source code files.
 #  Created   : Monday, November  9 2020.
 #  Author    : Pierre Rouleau <prouleau001@gmail.com>
-#  Time-stamp: <2025-04-25 09:27:09 EDT, updated by Pierre Rouleau>
+#  Time-stamp: <2025-04-25 13:50:12 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 #  Module Description
 #  ------------------
 #
 # Build an Emacs Tags file for all Python source code files in the
-# sub-directory tree.  This includes the .py and .pyw files.
-#
+# sub-directory tree.  This includes the .py and .pyw files and the
+# extension-less python script files.
 
 # ----------------------------------------------------------------------------
 #  Dependencies
@@ -35,11 +35,13 @@
 #   Universal Ctags executable file.
 
 # ----------------------------------------------------------------------------
-#  Code
-#  ----
+# Code
+# ----
 
 pgm_name="$(basename "$0")"
 pgm_path="$(dirname "$(readlink "$0")")"
+etags_flist_fname=.etags-py-files.txt
+etags_flist_envvar_fname="$ETAGS_FILE_LIST_FOR_PYTHON"
 
 print_usage()
 {
@@ -53,14 +55,19 @@ print_usage()
   • Print this help information.
 
  Usage: %s [-u] [DIRPATH ...]
+        %s [-u] [--list=FILENAME]
 
   • [Re]build an etags-compliant TAGS file in current directory
     for the Python source code files found:
     - in the DIRPATH directory tree(s) identified on the command line, or
-      the current directory if none is specified.
+      the current directory if none is specified, or
+    - in the list provided in the FILENAME specified by the --list option, or
+    - specified by the ETAGS_FILE_LIST_FOR_PYTHON environment variable.
   • Also lists all extension-less Python script files
     as well as Python files with the usual extensions.
   • Follows symbolic links both for directories and files.
+  • Uses etags to build the TAGS file by default, but
+    -u : force use Universal Ctags (ctags) instead of etags.
   • Overwrites any TAGS file in the current directory.
   • Uses etags to build the TAGS file by default, but
     -u : force use Universal Ctags (ctags) instead of etags.
@@ -88,7 +95,7 @@ print_usage()
   • The only output on stdout is the list of files found.
     This allows this script to be used as the first in a pipe
     to do other processing with the list of files found.
-" "$pgm_name" "$pgm_name" "$pgm_name"
+" "$pgm_name" "$pgm_name" "$pgm_name" "$pgm_name"
     if [ "$ETAGS_USE_FIND" = "1" ]; then
         printf -- "
 ⚠️   ETAGS_USE_FIND is currently set to 1, forcing the use of 'find'!
@@ -100,6 +107,16 @@ print_usage()
 }
 
 # --
+# run__etags__py -- run etags or ctags on a set of files
+# --------------
+#
+# Use etags to parse the source code files unless ETAGS_USE_UCTAGS
+# environment variable is set to 1.  In which case it uses ctags.
+# Ideally that would be the latest version of Universal ctags
+# from https://github.com/universal-ctags/ctags#readme as opposed to the
+# old and currently un-maintained Exeburant ctags.
+# When using Emacs, Emacs provides its own ctags that is essentially etags.
+# Etags generates a tag file format a little different and better suited for Emacs.
 
 run__etags__py()
 {
@@ -108,14 +125,14 @@ run__etags__py()
     if [ -n "$ETAGS_USE_UCTAGS" ]; then
         if [ "$ETAGS_USE_UCTAGS" = "1" ]; then
             xargs ctags --output-format=etags
-            printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n"  "$(which ctags)"
+            printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n" "$(which ctags)" 1>&2
         elif [ -x "$ETAGS_USE_UCTAGS" ]; then
             xargs "$ETAGS_USE_UCTAGS" --output-format=etags
-            printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n"  "$ETAGS_USE_UCTAGS"
+            printf "Note: ETAGS_USE_UCTAGS forced using %s to process files.\n"  "$ETAGS_USE_UCTAGS" 1>&2
         else
-            printf -- "*** ERROR: %s:  invalid ETAGS_USE_UCTAGS value\n" "${pgm_name}"
-            printf -- "***  ETAGS_USE_UCTAGS : %s\n" "$ETAGS_USE_UCTAGS"
-            printf -- "***  This is not 1 nor a valid executable file name.\n"
+            printf -- "*** ERROR: %s: invalid ETAGS_USE_UCTAGS value\n" "${pgm_name}" 1>&2
+            printf -- "***  ETAGS_USE_UCTAGS : %s\n" "$ETAGS_USE_UCTAGS" 1>&2
+            printf -- "***  This is not 1 nor a valid executable file name.\n" 1>&2
             exit 4
         fi
     else
@@ -136,59 +153,38 @@ if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
     fi
 fi
 
-# --
-
 # Check -u option to force use of universal ctags
 if [ "$1" = "-u" ]; then
     if [ -z "$ETAGS_USE_UCTAGS" ]; then
-        echo "etags-py: -u option requests use of Universal Ctags."
+        printf -- "%s: -u option requests use of Universal Ctags.\n" "${pgm_name}" 1>&2
         ETAGS_USE_UCTAGS=1
     else
-        echo "etags-py: -u option not necessary (but does no harm)."
-        echo " ETAGS_USE_UCTAGS is already set to: $ETAGS_USE_UCTAGS"
+        printf -- "%s: -u option not necessary (but does no harm).\n" "${pgm_name}" 1>&2
+        printf -- " ETAGS_USE_UCTAGS is already set to: %s\n" "$ETAGS_USE_UCTAGS" 1>&2
     fi
     shift
 fi
 
 # --
-# Check the validity of directory names specified as arguments.
-# Ensure that each directory specified on the command line
-# exists.  Also ensure that a directory name is not specified more
-# than once.  Use the realpath of that directory name when comparing.
+#  Check --list option to extract list of Python files.
 
-dpaths=
-for dname in "$@"; do
-    if [ ! -d "${dname}" ]; then
-        printf -- "Specified directory does not exists: %s\n" "${dname}"
-        exit 2
-    fi
-    dpath="$(realpath "${dname}")"
-    for dp in ${dpaths}; do
-        if [ "$dp" = "$dpath" ]; then
-            printf -- "Multiple entry of directory: %s\n" "${dname}"
-            exit 3
+case "$1" in
+    --list=*)
+    # extract the file name from the --list= option
+        fname="$(echo "$1" | sed 's/--list=//g')"
+        if [ ! -f "${fname}" ]; then
+            printf -- "\
+*** ERROR: %s: specified list file does not exist: %s
+" "${pgm_name}" "${fname}" 1>&2
+            exit 1
+        else
+            etags_flist_envvar_fname="${fname}"
+            shift
         fi
-        # check if new entry is a sub-directory of an exiting entry
-        case "${dpath}" in
-            "${dp}/"*)
-                printf -- "%s is a sub-dir of already specified %s\n" "${dname}" "${dp}"
-                exit 3
-                ;;
-        esac
-        # check if new entry is a parent directory of an existing entry
-        case "${dp}" in
-            "${dpath}/"*)
-                printf -- "%s is a parent dir of already specified %s\n" "${dname}" "${dp}"
-                exit 3
-                ;;
-        esac
+        ;;
+esac
 
-    done
-    dpaths="${dpaths} ${dpath}"
-done
-
-# --
-
+# ----------------------------------------------------------------------------
 # Define a function that searches into 1 directory
 # and accumulates the list of found files into the
 # file '.etags-py-files.txt'.
@@ -213,7 +209,7 @@ search_with_find()
     find -L ${find_path_option} "$dirname" \( \
          -name     "*.py" \
          -or -name "*.pyw" \
-         \)  -print | tee -a .etags-py-files.txt
+         \)  -print | tee -a "${etags_flist_fname}"
 }
 
 search_with_fd()
@@ -221,7 +217,7 @@ search_with_fd()
     # Arg: dirname : name of directory tree to search
     # Arg: fd_pgm  : fd or fdfind
     ${fd_pgm} -L --type f -e .py -e .pyw \
-              '' "$dirname" | tee -a .etags-py-files.txt
+              '' "$dirname" | tee -a "${etags_flist_fname}"
 }
 
 search()
@@ -242,73 +238,130 @@ search()
 search_script()
 {
     # Arg: dirname : name of directory tree to search
-    "${pgm_path}/find-script-py"  "$dirname" | tee -a .etags-py-files.txt
+    "${pgm_path}/find-script-py"  "$dirname" | tee -a "${etags_flist_fname}"
 }
 
-
 # --
-# First prepare environment
-# Select the method to search for files.
-# - Try to use fd or fdfind if they exist,
-#   otherwise use find.
-# - Echo the actual program used to find files (on stderr).
-if [ "$ETAGS_USE_FIND" = "1" ]; then
-    search_with='find'
-    echo "- ETAGS_USE_FIND forces the use of find!" 1>&2
-    echo "-> Using" "$(which find)"                 1>&2
-else
-    if [ -x "$(command -v fdfind)" ]; then
-        search_with='fd'
-        fd_pgm=fdfind
-        echo "-> Using" "$(which fdfind)" 1>&2
-        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
-    elif [ -x "$(command -v fd)" ]; then
-        search_with='fd'
-        fd_pgm=fd
-        echo "-> Using" "$(which fd)" 1>&2
-        echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
-    else
-        search_with='find'
-        echo "-> Using" "$(which find)" 1>&2
+# Proceed
+
+if [ -n "${etags_flist_envvar_fname}" ]; then
+    if [ "${etags_flist_envvar_fname}" = "${etags_flist_fname}" ]; then
+        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_PYTHON to %s\n" "${pgm_name}" "${etags_flist_fname}"1>&2
+        exit 1
     fi
-fi
-
-# -- proceed
-# remove the old list of files.
-rm -f .etags-py-files.txt
-
-# Search in all specified directory to build the list of
-# files in the file '.etags-py-files.txt'.
-# Use find-script-py to identify the names of the extension-less
-# Python files.  This script is inside the same directory as etags-py.
-
-printf -- "Files found printed in found order (not necessarily in sorted order)\n" 1>&2
-if [ -z "$1" ]; then
-    dirname="."
-    search
-    search_script
+    printf -- "Using the file list identified by ETAGS_FILE_LIST_FOR_PYTHON: %s\n" "${etags_flist_envvar_fname}" 1>&2
+    cp "${etags_flist_envvar_fname}" "${etags_flist_fname}"
+    run__etags__python < "${etags_flist_envvar_fname}"
 else
-    for dirname in "$@"; do
+    # Check the validity of directory names specified as arguments.
+    # Ensure that each directory specified on the command line
+    # exists.  Also ensure that a directory name is not specified more
+    # than once.  Use the realpath of that directory name when comparing.
+    # Exit on the first error detected.
+    dpaths=
+    for dname in "$@"; do
+        if [ ! -d "${dname}" ]; then
+            printf -- "Specified directory does not exists: %s\n" "${dname}" 1>&2
+            exit 2
+        fi
+        dpath="$(realpath "${dname}")"
+        for dp in ${dpaths}; do
+            if [ "$dp" = "$dpath" ]; then
+                printf -- "Multiple entry of directory: %s\n" "${dname}" 1>&2
+                exit 3
+            fi
+            # check if new entry is a sub-directory of an exiting entry
+            case "${dpath}" in
+                "${dp}/"*)
+                    printf -- "%s is a sub-dir of already specified %s\n" "${dname}" "${dp}" 1>&2
+                    exit 3
+                    ;;
+            esac
+            # check if new entry is a parent directory of an existing entry
+            case "${dp}" in
+                "${dpath}/"*)
+                    printf -- "%s is a parent dir of already specified %s\n" "${dname}" "${dp}" 1>&2
+                    exit 3
+                    ;;
+            esac
+        done
+        dpaths="${dpaths} ${dpath}"
+    done
+
+    # --
+    # First prepare environment
+    # Select the method to search for files.
+    # - Try to use fd or fdfind if they exist,
+    #   otherwise use find.
+    # - Echo the actual program used to find files (on stderr).
+    if [ "$ETAGS_USE_FIND" = "1" ]; then
+        search_with='find'
+        echo "- ETAGS_USE_FIND forces the use of find!" 1>&2
+        echo "-> Using" "$(which find)"                 1>&2
+    else
+        if [ -x "$(command -v fdfind)" ]; then
+            search_with='fd'
+            fd_pgm=fdfind
+            echo "-> Using" "$(which fdfind)" 1>&2
+            echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
+        elif [ -x "$(command -v fd)" ]; then
+            search_with='fd'
+            fd_pgm=fd
+            echo "-> Using" "$(which fd)" 1>&2
+            echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore" 1>&2
+        else
+            search_with='find'
+            echo "-> Using" "$(which find)" 1>&2
+        fi
+    fi
+
+    printf --  "No list of files identified by ETAGS_FILE_LIST_FOR_PYTHON.\n" 1>&2
+    printf -- "Files found printed in found order (not necessarily in sorted order)\n" 1>&2
+
+    # -- proceed
+    # Rename the old list of files if it exists
+    if [ -e "${etags_flist_fname}" ]; then
+        mv "${etags_flist_fname}" "${etags_flist_fname}.backup"
+    fi
+
+    # Search in all specified directory to build the list of
+    # files in the file '.etags-py-files.txt'.
+    if [ -z "$1" ]; then
+        dirname="."
         search
         search_script
-    done
+    else
+        for dirname in "$@"; do
+            search
+            search_script
+        done
+    fi
+
+    # Then run etags on these files, and sort them in the etags file
+    sort < "${etags_flist_fname}" | uniq >  "${etags_flist_fname}.new"
+    rm -f "${etags_flist_fname}"
+    mv "${etags_flist_fname}.new" "${etags_flist_fname}"
+    run__etags__rust < "${etags_flist_fname}"
 fi
 
-# Then run etags on these files, and sort them in the etags file
-sort < .etags-py-files.txt | uniq >  .etags-py-files.1.txt
-rm -f .etags-py-files.txt
-mv .etags-py-files.1.txt .etags-py-files.txt
-run__etags__py < .etags-py-files.txt
+file_count="$(wc -l "${etags_flist_fname}" | awk '{print $1}')"
+if [ "$file_count" = "0" ]; then
+    # restore the old list of files.
+    rm -rf "${etags_flist_fname}"
+    if [ -e "${etags_flist_fname}.backup" ]; then
+        mv "${etags_flist_fname}.backup"  "${etags_flist_fname}"
+    fi
+    printf -- "No files found. %s and TAGS files untouched.\n" "${etags_flist_fname}"  1>&2
+    exit 1
+else
+  rm -rf "${etags_flist_fname}.backup"
+  printf "\
+  %s - %s files found and processed.
+             Created: %s/TAGS
+             Scanned file list stored in: %s/%s\n" "${pgm_name}" "${file_count}" "$(pwd)" "$(pwd)" "${etags_flist_fname}" 1>&2
+fi
 
-
-file_count="$(wc -l .etags-py-files.txt | awk '{print $1}')"
-printf "\
-%s - %s files found and processed.
-           Created: %s/TAGS
-           Scanned file list stored in: %s/.etags-py-files.txt
-" "${pgm_name}" "${file_count}" "$(pwd)" "$(pwd)" 1>&2
-
-# -----------------------------------------------------------------------------
+# ----------------------------------------------------------------------------
 # Local Variables:
 # sh-shell: sh
 # End:
