Cleanup, making code more common across

diff --git a/bin/etags-go b/bin/etags-go
--- a/bin/etags-go
+++ b/bin/etags-go
@@ -4,7 +4,7 @@
 #  Purpose   : Build Emacs Tags file for Go source code files.
 #  Created   : Thursday, June 6, 2024
 #  Author    : Pierre Rouleau <prouleau001@gmail.com>
-#  Time-stamp: <2025-04-25 00:04:04 EDT, updated by Pierre Rouleau>
+#  Time-stamp: <2025-04-25 08:53:22 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 #  Module Description
 #  ------------------
@@ -131,6 +131,7 @@ if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
     fi
 fi
 
+# Check -u option to force use of universal ctags
 if [ "$1" = "-u" ]; then
     if [ -z "$ETAGS_USE_UCTAGS" ]; then
         printf --  "%s: -u option requests use of Universal Ctags.\n" "${pgm_name}" 1>&2
@@ -184,12 +185,26 @@ done
 # and accumulates the list of found files into the
 # file '.etags-go-files.txt'.
 
+# Identify options
+case $(uname) in
+    Darwin)
+        find_path_option='-f'
+        ;;
+    Linux)
+        find_path_option=
+        ;;
+    *)
+        printf -- "*** ERROR: %s:  Error Operating System, %s, is not supported!\n" "${pgm_name}"  "$(uname)" 1>&2
+        exit 1
+        ;;
+esac
+
 search_with_find()
 {
     # Arg: dirname : name of directory tree to search
 
-    find -f "$dirname" \( \
-         -name     "*.go" \
+    find -L ${find_path_option} "$dirname" \( \
+         -name "*.go" \
          \)  -print | tee -a .etags-go-files.txt
 }
 
@@ -198,7 +213,7 @@ search_with_fd()
     # Arg: dirname : name of directory tree to search
     # Arg: fd_pgm  : fd or fdfind
 
-    ${fd_pgm} --type f -e .go \
+    ${fd_pgm} -L --type f -e .go \
            "$dirname" | tee -a .etags-go-files.txt
 }
 
diff --git a/bin/etags-make b/bin/etags-make
--- a/bin/etags-make
+++ b/bin/etags-make
@@ -4,7 +4,7 @@
 #  Purpose   : Build Emacs Tags file for Make source code files.
 #  Created   : Thursday, June 6, 2024
 #  Author    : Pierre Rouleau <prouleau001@gmail.com>
-#  Time-stamp: <2025-04-24 23:59:26 EDT, updated by Pierre Rouleau>
+#  Time-stamp: <2025-04-25 07:41:33 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 #  Module Description
 #  ------------------
@@ -127,6 +127,7 @@ if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
     fi
 fi
 
+# Check -u option to force use of universal ctags
 if [ "$1" = "-u" ]; then
     if [ -z "$ETAGS_USE_UCTAGS" ]; then
         printf -- "%s: -u option requests use of Universal Ctags.\n" "${pgm_name}" 1>&2
@@ -180,11 +181,26 @@ done
 # and accumulates the list of found files into the
 # file '.etags-make-files.txt'.
 
+# Identify options
+case $(uname) in
+    Darwin)
+        find_path_option='-f'
+        ;;
+    Linux)
+        find_path_option=
+        ;;
+    *)
+        printf -- "*** ERROR: %s:  Error Operating System, %s, is not supported!\n" "${pgm_name}"  "$(uname)" 1>&2
+        exit 1
+        ;;
+esac
+
+
 search_with_find()
 {
     # Arg: dirname : name of directory tree to search
 
-    find -L -f "$dirname" \( \
+    find -L ${find_path_option} "$dirname" \( \
          -name     "Makefile" \
          -or -name "makefile" \
          -or -name "GNUMakefile" \
diff --git a/bin/etags-py b/bin/etags-py
--- a/bin/etags-py
+++ b/bin/etags-py
@@ -4,7 +4,7 @@
 #  Purpose   : Build Emacs Tags file for Python source code files.
 #  Created   : Monday, November  9 2020.
 #  Author    : Pierre Rouleau <prouleau001@gmail.com>
-#  Time-stamp: <2025-04-24 23:46:14 EDT, updated by Pierre Rouleau>
+#  Time-stamp: <2025-04-25 08:12:20 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 #  Module Description
 #  ------------------
@@ -138,6 +138,7 @@ fi
 
 # --
 
+# Check -u option to force use of universal ctags
 if [ "$1" = "-u" ]; then
     if [ -z "$ETAGS_USE_UCTAGS" ]; then
         echo "etags-py: -u option requests use of Universal Ctags."
@@ -192,10 +193,24 @@ done
 # and accumulates the list of found files into the
 # file '.etags-py-files.txt'.
 
+# Identify options
+case $(uname) in
+    Darwin)
+        find_path_option='-f'
+        ;;
+    Linux)
+        find_path_option=
+        ;;
+    *)
+        printf -- "*** ERROR: %s:  Error Operating System, %s, is not supported!\n" "${pgm_name}"  "$(uname)" 1>&2
+        exit 1
+        ;;
+esac
+
 search_with_find()
 {
     # Arg: dirname : name of directory tree to search
-    find -L -f "$dirname" \( \
+    find -L ${find_path_option} "$dirname" \( \
          -name     "*.py" \
          -or -name "*.pyw" \
          \)  -print | tee -a .etags-py-files.txt
@@ -223,6 +238,13 @@ search()
             ;;
     esac
 }
+
+search_script()
+{
+    # Arg: dirname : name of directory tree to search
+    "${pgm_path}/find-script-py"  "$dirname" | tee -a .etags-py-files.txt
+}
+
 
 # --
 # First prepare environment
@@ -264,11 +286,11 @@ printf -- "Files found printed in found order (not necessarily in sorted order)\
 if [ -z "$1" ]; then
     dirname="."
     search
-    "${pgm_path}/find-script-py" | tee -a .etags-py-files.txt
+    search_script
 else
     for dirname in "$@"; do
         search
-       "${pgm_path}/find-script-py"  "$dirname" | tee -a .etags-py-files.txt
+        search_script
     done
 fi
 
