Fix typos, code & logic errors in scripts

diff --git a/bin/etags-c b/bin/etags-c
--- a/bin/etags-c
+++ b/bin/etags-c
@@ -4,7 +4,7 @@
 #  Purpose   : Build Emacs Tags file for C/C++ source code files.
 #  Created   : Monday, November  9 2020.
 #  Author    : Pierre Rouleau <prouleau001@gmail.com>
-#  Time-stamp: <2026-03-13 14:18:49 EDT, updated by Pierre Rouleau>
+#  Time-stamp: <2026-03-13 15:48:11 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 #  Module Description
 #  ------------------
@@ -321,7 +321,7 @@ if [ -n "${etags_flist_envvar_fname}" ]; then
     # invoking etags-c then use that if possible: that variable should
     # identify a file name different than what we use internally.
     if [ "${etags_flist_envvar_fname}" = "${etags_flist_fname}" ]; then
-        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_C to %s\n" "${pgm_name}" "${etags_flist_fname}"1>&2
+        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_C to %s\n" "${pgm_name}" "${etags_flist_fname}" 1>&2
         printf -- "           Use a different file name!\n" 1>&2
         exit 1
     fi
diff --git a/bin/etags-erl b/bin/etags-erl
--- a/bin/etags-erl
+++ b/bin/etags-erl
@@ -4,7 +4,7 @@
 #  Purpose   : Build Emacs Tags file for Erlang and C source code files.
 #  Created   : Monday, November  9 2020.
 #  Author    : Pierre Rouleau <prouleau001@gmail.com>
-#  Time-stamp: <2026-03-13 14:18:48 EDT, updated by Pierre Rouleau>
+#  Time-stamp: <2026-03-13 15:49:01 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 #  Module Description
 #  ------------------
@@ -211,7 +211,7 @@ search_with_find()
     find -L ${find_path_option} "$dirname" \
          \( -name "*.[ch]"                 \
          \) -print | tee -a "${etags_flist_fname}"
-    find -L -f "$dirname"          \
+    find -L ${find_path_option}  "$dirname" \
          \(  -name "*\.[he]rl"     \
          -or -name "*\.app"        \
          -or -name "*\.app.src"    \
@@ -260,7 +260,7 @@ search_script()
 
 if [ -n "${etags_flist_envvar_fname}" ]; then
     if [ "${etags_flist_envvar_fname}" = "${etags_flist_fname}" ]; then
-        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_ERLANG to %s\n" "${pgm_name}" "${etags_flist_fname}"1>&2
+        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_ERLANG to %s\n" "${pgm_name}" "${etags_flist_fname}" 1>&2
         exit 1
     fi
     printf -- "Using the file list identified by ETAGS_FILE_LIST_FOR_ERLANG: %s\n" "${etags_flist_envvar_fname}" 1>&2
diff --git a/bin/etags-go b/bin/etags-go
--- a/bin/etags-go
+++ b/bin/etags-go
@@ -4,7 +4,7 @@
 #  Purpose   : Build Emacs Tags file for Go source code files.
 #  Created   : Thursday, June 6, 2024
 #  Author    : Pierre Rouleau <prouleau001@gmail.com>
-#  Time-stamp: <2026-03-13 14:18:48 EDT, updated by Pierre Rouleau>
+#  Time-stamp: <2026-03-13 15:53:03 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 #  Module Description
 #  ------------------
@@ -176,7 +176,7 @@ if [ "$1" = "-n" ]; then
 fi
 
 # --
-#  Check --list option to extract list of Rust files.
+#  Check --list option to extract list of Go files.
 
 case "$1" in
     --list=*)
@@ -251,10 +251,10 @@ search()
 
 if [ -n "${etags_flist_envvar_fname}" ]; then
     # If the ETAGS_FILE_LIST_FOR_GO environment variable was set in the shell
-    # invoking etags-py then use that if possible: that variable should
+    # invoking etags-go then use that if possible: that variable should
     # identify a file name different than what we use internally.
     if [ "${etags_flist_envvar_fname}" = "${etags_flist_fname}" ]; then
-        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_GO to %s\n" "${pgm_name}" "${etags_flist_fname}"1>&2
+        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_GO to %s\n" "${pgm_name}" "${etags_flist_fname}" 1>&2
         printf -- "           Use a different file name!\n" 1>&2
         exit 1
     fi
diff --git a/bin/etags-javascript b/bin/etags-javascript
--- a/bin/etags-javascript
+++ b/bin/etags-javascript
@@ -4,7 +4,7 @@
 # Purpose   : Build Emacs Tags file for Javascript source code files.
 # Created   : Monday, October 27 2025.
 # Author    : Pierre Rouleau <prouleau001@gmail.com>
-# Time-stamp: <2026-03-13 14:18:48 EDT, updated by Pierre Rouleau>
+# Time-stamp: <2026-03-13 15:51:27 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 
 #  Module Description
@@ -243,11 +243,11 @@ if [ -n "${etags_flist_envvar_fname}" ]; then
     # invoking etags-javascript then use that if possible: that variable should
     # identify a file name different than what we use internally.
     if [ "${etags_flist_envvar_fname}" = "${etags_flist_fname}" ]; then
-        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_JAVASCRIPT to %s\n" "${pgm_name}" "${etags_flist_fname}"1>&2
+        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_JAVASCRIPT to %s\n" "${pgm_name}" "${etags_flist_fname}" 1>&2
         printf -- "           Use a different file name!\n" 1>&2
         exit 1
     fi
-    printf -- "Using the file list identified by ETAGS_FILE_LIST_FOR_AUTOTOOLS: %s\n" "${etags_flist_envvar_fname}" 1>&2
+    printf -- "Using the file list identified by ETAGS_FILE_LIST_FOR_JAVASCRIPT: %s\n" "${etags_flist_envvar_fname}" 1>&2
     cp "${etags_flist_envvar_fname}" "${etags_flist_fname}"
     printf -- "Generating TAGS ...\n" 1>&2
     run__etags__javascript < "${etags_flist_envvar_fname}"
@@ -314,7 +314,7 @@ else
         fi
     fi
 
-    printf -- "No list of files identified by ETAGS_FILE_LIST_FOR_AUTOTOOLS.\n" 1>&2
+    printf -- "No list of files identified by ETAGS_FILE_LIST_FOR_JAVASCRIPT.\n" 1>&2
     printf -- "Files found printed in found order (not necessarily in sorted order)\n" 1>&2
 
     # -- proceed
diff --git a/bin/etags-objc b/bin/etags-objc
--- a/bin/etags-objc
+++ b/bin/etags-objc
@@ -4,7 +4,7 @@
 # Purpose   : Build Emacs Tags files for Objective-C code files.
 # Created   : Friday, December  5 2025.
 # Author    : Pierre Rouleau <prouleau001@gmail.com>
-# Time-stamp: <2026-03-13 14:18:47 EDT, updated by Pierre Rouleau>
+# Time-stamp: <2026-03-13 15:52:24 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 
 # Module Description
@@ -292,11 +292,11 @@ if [ -n "${etags_flist_envvar_fname}" ]; then
     # invoking etags-c then use that if possible: that variable should
     # identify a file name different than what we use internally.
     if [ "${etags_flist_envvar_fname}" = "${etags_flist_fname}" ]; then
-        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_OBJC to %s\n" "${pgm_name}" "${etags_flist_fname}"1>&2
+        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_OBJC to %s\n" "${pgm_name}" "${etags_flist_fname}" 1>&2
         printf -- "           Use a different file name!\n" 1>&2
         exit 1
     fi
-    printf -- "Using the file list identified by ETAGS_FILE_LIST_FOR_C: %s\n" "${etags_flist_envvar_fname}" 1>&2
+    printf -- "Using the file list identified by ETAGS_FILE_LIST_FOR_OBJC: %s\n" "${etags_flist_envvar_fname}" 1>&2
     cp "${etags_flist_envvar_fname}" "${etags_flist_fname}"
     printf -- "Generating TAGS ...\n" 1>&2
     run__etags__objc < "${etags_flist_envvar_fname}"
@@ -375,7 +375,7 @@ else
             exit 1
             ;;
     esac
-    printf --  "No list of files identified by ETAGS_FILE_LIST_FOR_C.\n" 1>&2
+    printf --  "No list of files identified by ETAGS_FILE_LIST_FOR_OBJC.\n" 1>&2
     printf -- "Files found printed in found order (not necessarily in sorted order)\n" 1>&2
 
     # -- proceed
diff --git a/bin/etags-perl b/bin/etags-perl
--- a/bin/etags-perl
+++ b/bin/etags-perl
@@ -4,7 +4,7 @@
 # Purpose   : Build Emacs Tags file for Perl source code files.
 # Created   : Tuesday, October  8 2024.
 # Author    : Pierre Rouleau <prouleau001@gmail.com>
-# Time-stamp: <2026-03-13 14:18:47 EDT, updated by Pierre Rouleau>
+# Time-stamp: <2026-03-13 15:48:10 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 # Module Description
 # ------------------
@@ -304,7 +304,7 @@ if [ -n "${etags_flist_envvar_fname}" ]; then
     # invoking etags-perl then use that if possible: that variable should
     # identify a file name different than what we use internally.
     if [ "${etags_flist_envvar_fname}" = "${etags_flist_fname}" ]; then
-        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_PERL to %s\n" "${pgm_name}" "${etags_flist_fname}"1>&2
+        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_PERL to %s\n" "${pgm_name}" "${etags_flist_fname}" 1>&2
         printf -- "           Use a different file name!\n" 1>&2
         exit 1
     fi
diff --git a/bin/etags-pike b/bin/etags-pike
--- a/bin/etags-pike
+++ b/bin/etags-pike
@@ -1,12 +1,10 @@
 #!/bin/sh
-#  SH FILE: etags-rs
-#
 #  SH FILE: etags-pike
 #
 #  Purpose   : Build Emacs Tags file for Pike & C/C++ source code files.
 #  Created   : Friday, March 21 2025.
 #  Author    : Pierre Rouleau <prouleau001@gmail.com>
-#  Time-stamp: <2025-03-21 21:43:38 EDT, updated by Pierre Rouleau>
+#  Time-stamp: <2026-03-13 15:57:32 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 #  Module Description
 #  ------------------
@@ -80,7 +78,7 @@ print_usage()
   • Overwrites any TAGS file in the current directory.
   • Inspects content of C, Pike and extension-less pike script files.
   • Stores the names of inspected files in the file named
-    .etags-rs-files.txt in the current directory.
+    .etags-pike-files.txt in the current directory.
   • Uses fast 'fdfind' or 'fd' if available, 'find' otherwise.
     - The 'fd' utility is from: https://github.com/sharkdp/fd
     - In some Linux distros, 'fd' is renamed 'fdfind'.
@@ -162,16 +160,11 @@ if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
     else
         exit  1
     fi
-elif [ "$1" = "-n" ]; then
-    build_tags=false
-    shift
-fi
-if [ "$1" = "-n" ]; then
-    build_tags=false
-    shift
 fi
 
 # Check -u option to force use of universal ctags
+# Check -n option: if specified do not build TAGS file and append to .etags-pike-files.txt
+# Note that we can have -u -n, -u, or -n: so handle all possible cases.
 if [ "$1" = "-u" ]; then
     if [ -z "$ETAGS_USE_UCTAGS" ]; then
         printf -- "%s: -u option requests use of Universal Ctags.\n" "${pgm_name}" 1>&2
@@ -180,6 +173,13 @@ if [ "$1" = "-u" ]; then
         printf -- "%s: -u option not necessary (but does no harm).\n" "${pgm_name}" 1>&2
         printf -- " ETAGS_USE_UCTAGS is already set to: %s\n" "$ETAGS_USE_UCTAGS" 1>&2
     fi
+    shift
+elif [ "$1" = "-n" ]; then
+    build_tags=false
+    shift
+fi
+if [ "$1" = "-n" ]; then
+    build_tags=false
     shift
 fi
 
@@ -205,7 +205,7 @@ esac
 # ----------------------------------------------------------------------------
 # Define a function that searches into 1 directory
 # and accumulates the list of found files into the
-# file '.etags-rs-files.txt'.
+# file '.etags-pike-files.txt'.
 
 # Identify options
 case $(uname) in
@@ -314,7 +314,7 @@ if [ -n "${etags_flist_envvar_fname}" ]; then
     # invoking etags-pike then use that if possible: that variable should
     # identify a file name different than what we use internally.
     if [ "${etags_flist_envvar_fname}" = "${etags_flist_fname}" ]; then
-        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_PIKE to %s\n" "${pgm_name}" "${etags_flist_fname}"1>&2
+        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_PIKE to %s\n" "${pgm_name}" "${etags_flist_fname}" 1>&2
         printf -- "           Use a different file name!\n" 1>&2
         exit 1
     fi
@@ -397,7 +397,7 @@ else
     fi
 
     # Search in all specified directory to build the list of
-    # files in the file '.etags-rs-files.txt'.
+    # files in the file '.etags-pike-files.txt'.
     if [ -z "$1" ]; then
         dirname="."
         search
diff --git a/bin/etags-tcl b/bin/etags-tcl
--- a/bin/etags-tcl
+++ b/bin/etags-tcl
@@ -4,7 +4,7 @@
 # Purpose   : Build Emacs Tags file for Tcl source code files.
 # Created   : Monday, October 27 2025.
 # Author    : Pierre Rouleau <prouleau001@gmail.com>
-# Time-stamp: <2026-03-13 14:18:47 EDT, updated by Pierre Rouleau>
+# Time-stamp: <2026-03-13 15:58:52 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 
 #  Module Description
@@ -15,7 +15,7 @@
 # - .itk
 # - .itcl
 # - .tcl
-# - mix.lock
+# - .exp
 
 # ----------------------------------------------------------------------------
 #  Dependencies
@@ -219,6 +219,7 @@ search_with_fd()
     #       it will take the directory name as a regexp...
     ${fd_pgm} -L --type f -e .itk -e .itcl -e .tcl  -e .exp\
               '' "$dirname" | tee -a "${etags_flist_fname}"
+}
 
 search()
 {
@@ -243,11 +244,11 @@ if [ -n "${etags_flist_envvar_fname}" ]; then
     # invoking etags-tcl then use that if possible: that variable should
     # identify a file name different than what we use internally.
     if [ "${etags_flist_envvar_fname}" = "${etags_flist_fname}" ]; then
-        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_TCL to %s\n" "${pgm_name}" "${etags_flist_fname}"1>&2
+        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_TCL to %s\n" "${pgm_name}" "${etags_flist_fname}" 1>&2
         printf -- "           Use a different file name!\n" 1>&2
         exit 1
     fi
-    printf -- "Using the file list identified by ETAGS_FILE_LIST_FOR_AUTOTOOLS: %s\n" "${etags_flist_envvar_fname}" 1>&2
+    printf -- "Using the file list identified by ETAGS_FILE_LIST_FOR_TCL: %s\n" "${etags_flist_envvar_fname}" 1>&2
     cp "${etags_flist_envvar_fname}" "${etags_flist_fname}"
     printf -- "Generating TAGS ...\n" 1>&2
     run__etags__tcl < "${etags_flist_envvar_fname}"
@@ -314,7 +315,7 @@ else
         fi
     fi
 
-    printf -- "No list of files identified by ETAGS_FILE_LIST_FOR_AUTOTOOLS.\n" 1>&2
+    printf -- "No list of files identified by ETAGS_FILE_LIST_FOR_TCL.\n" 1>&2
     printf -- "Files found printed in found order (not necessarily in sorted order)\n" 1>&2
 
     # -- proceed
