Add -n option to etags-perl

diff --git a/bin/etags-perl b/bin/etags-perl
--- a/bin/etags-perl
+++ b/bin/etags-perl
@@ -4,7 +4,7 @@
 # Purpose   : Build Emacs Tags file for Perl source code files.
 # Created   : Tuesday, October  8 2024.
 # Author    : Pierre Rouleau <prouleau001@gmail.com>
-# Time-stamp: <2025-04-30 19:28:28 EDT, updated by Pierre Rouleau>
+# Time-stamp: <2025-09-03 14:27:18 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 # Module Description
 # ------------------
@@ -20,6 +20,8 @@
 # Dependencies
 # ------------
 
+# - etags
+# - xargs, printf, uname, sort, uniq, find, rm.
 # - Uses fd (also named fdfind in some Linux distros like Mint) if it is
 #   available.  See URL:  https://github.com/sharkdp/fd .
 # - if fd/fdfind is not available, use find instead.
@@ -46,7 +48,8 @@
 pgm_name="$(basename "$0")"
 pgm_path="$(dirname "$(readlink "$0")")"
 etags_flist_fname=.etags-perl-files.txt
-etags_flist_envvar_fname="$ETAGS_PERL_FILE_LIST"
+etags_flist_envvar_fname="$ETAGS_FILE_LIST_FOR_PERL"
+build_tags=true
 
 print_usage()
 {
@@ -71,7 +74,7 @@ print_usage()
  Usage: %s h|--help
   • Print this help information.
 
- Usage: %s [-u] [DIRPATH ...]
+ Usage: %s [-u] [-n] [DIRPATH ...]
         %s [-u] [--list=FILENAME]
 
   • [Re]build an etags-compliant TAGS file in the current directory
@@ -79,13 +82,13 @@ print_usage()
     - in the DIRPATH directory tree(s) identified on the command line, or
       the current directory if none is specified, or
     - in the list provided in the FILENAME specified by the --list option, or
-    - specified by the ETAGS_PERL_FILE_LIST environment variable.
+    - specified by the ETAGS_FILE_LIST_FOR_PERL environment variable.
   • Follows symbolic links both for directories and files.
   • Overwrites any TAGS file in the current directory.
   • Stores the names of inspected files in the file named
      %s in the current directory.
   • Identifies the Perl files using one of the following methods:
-    • If ETAGS_PERL_FILE_LIST environment variable exists, it uses it as
+    • If ETAGS_FILE_LIST_FOR_PERL environment variable exists, it uses it as
       the name of a file that holds a list of Perl files to parse.
       The name of this file can be anything except %s
       and it must exists. It it does not %s exists with an error.
@@ -106,6 +109,11 @@ print_usage()
       Ctags executable file to force using Universal Ctags instead.
       When setting it to 1, the ctags found in PATH is expected
       to be Universal Ctags.
+  • -n : do not create TAGS file, just add names of Perl
+         source code files into the .etags-perl-files.txt
+         file.  Use this option to create the list of source
+         files in multiple commands and then later the
+         etags-perl --list to create the TAGS file.
   • Info printed on stderr:
    • The path of the find program used and when repository ignore files
      are skipped from the scan.
@@ -172,6 +180,8 @@ if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
 fi
 
 # Check -u option to force use of universal ctags
+# Check -n option: if specified do not build TAGS file and append to .etags-perl-files.txt
+# Note that we can have -u -n, -u, or -n: so handle all possible cases.
 if [ "$1" = "-u" ]; then
     if [ -z "$ETAGS_USE_UCTAGS" ]; then
         printf -- "%s: -u option requests use of Universal Ctags.\n" "${pgm_name}" 1>&2
@@ -180,6 +190,13 @@ if [ "$1" = "-u" ]; then
         printf -- "%s: -u option not necessary (but does no harm).\n" "${pgm_name}" 1>&2
         printf -- " ETAGS_USE_UCTAGS is already set to: %s\n" "$ETAGS_USE_UCTAGS" 1>&2
     fi
+    shift
+elif [ "$1" = "-n" ]; then
+    build_tags=false
+    shift
+fi
+if [ "$1" = "-n" ]; then
+    build_tags=false
     shift
 fi
 
@@ -196,7 +213,7 @@ case "$1" in
 " "${pgm_name}" "${fname}" 1>&2
             exit 1
         else
-            ETAGS_PERL_FILE_LIST="${fname}"
+            ETAGS_FILE_LIST_FOR_PERL="${fname}"
             shift
         fi
         ;;
@@ -283,11 +300,15 @@ search_script()
 # Proceed
 
 if [ -n "${etags_flist_envvar_fname}" ]; then
+    # If the ETAGS_FILE_LIST_FOR_PERL environment variable was set in the shell
+    # invoking etags-perl then use that if possible: that variable should
+    # identify a file name different than what we use internally.
     if [ "${etags_flist_envvar_fname}" = "${etags_flist_fname}" ]; then
-        printf -- "*** ERROR: %s: Do NOT set ETAGS_PERL_FILE_LIST to %s\n" "${pgm_name}" "${etags_flist_fname}"1>&2
+        printf -- "*** ERROR: %s: Do NOT set ETAGS_FILE_LIST_FOR_PERL to %s\n" "${pgm_name}" "${etags_flist_fname}"1>&2
+        printf -- "           Use a different file name!\n" 1>&2
         exit 1
     fi
-    printf -- "Using the file list identified by ETAGS_PERL_FILE_LIST: %s\n" "${etags_flist_envvar_fname}" 1>&2
+    printf -- "Using the file list identified by ETAGS_FILE_LIST_FOR_PERL: %s\n" "${etags_flist_envvar_fname}" 1>&2
     cp "${etags_flist_envvar_fname}" "${etags_flist_fname}"
     printf -- "Generating TAGS ...\n" 1>&2
     run__etags__perl < "${etags_flist_envvar_fname}"
@@ -329,7 +350,7 @@ else
         dpaths="${dpaths} ${dpath}"
     done
 
-    printf --  "No list of files identified by ETAGS_PERL_FILE_LIST.\n" 1>&2
+    printf --  "No list of files identified by ETAGS_FILE_LIST_FOR_PERL.\n" 1>&2
     printf --  "- Building the list of source files.\n" 1>&2
 
     # --
@@ -362,9 +383,11 @@ else
 
 
     # -- proceed
-    # Rename the old list of files if it exists
-    if [ -e "${etags_flist_fname}" ]; then
-        mv "${etags_flist_fname}" "${etags_flist_fname}.backup"
+    # Rename the old list of files if it exists and TAGS will be built
+    if [ "${build_tags}" = "true" ]; then
+        if [ -e "${etags_flist_fname}" ]; then
+            mv "${etags_flist_fname}" "${etags_flist_fname}.backup"
+        fi
     fi
 
     printf -- "Files found printed in found order (not necessarily in sorted order)\n" 1>&2
@@ -379,29 +402,36 @@ else
         done
     fi
 
-    # Then run etags on these files, and sort them in the etags file
-    sort < "${etags_flist_fname}" | uniq >  "${etags_flist_fname}.new"
-    rm -f "${etags_flist_fname}"
-    mv "${etags_flist_fname}.new" "${etags_flist_fname}"
-    printf -- "Generating TAGS ...\n" 1>&2
-    run__etags__perl < "${etags_flist_fname}"
+    # If required, run etags on these files, and sort them in the etags file
+    if [ "${build_tags}" = "true" ]; then
+        # Then run etags on these files, and sort them in the etags file
+        sort < "${etags_flist_fname}" | uniq >  "${etags_flist_fname}.new"
+        rm -f "${etags_flist_fname}"
+        mv "${etags_flist_fname}.new" "${etags_flist_fname}"
+        printf -- "Generating TAGS ...\n" 1>&2
+        run__etags__perl < "${etags_flist_fname}"
+    fi
 fi
 
-file_count="$(wc -l "${etags_flist_fname}" | awk '{print $1}')"
-if [ "$file_count" = "0" ]; then
-    # restore the old list of files.
-    rm -rf "${etags_flist_fname}"
-    if [ -e "${etags_flist_fname}.backup" ]; then
-        mv "${etags_flist_fname}.backup"  "${etags_flist_fname}"
-    fi
-    printf -- "No files found. %s and TAGS files untouched.\n" "${etags_flist_fname}"  1>&2
-    exit 1
-else
-  rm -rf "${etags_flist_fname}.backup"
-  printf "\
+if [ "${build_tags}" = "true" ]; then
+    file_count="$(wc -l "${etags_flist_fname}" | awk '{print $1}')"
+    if [ "$file_count" = "0" ]; then
+        # restore the old list of files.
+        rm -f "${etags_flist_fname}"
+        if [ -e "${etags_flist_fname}.backup" ]; then
+            mv "${etags_flist_fname}.backup"  "${etags_flist_fname}"
+        fi
+        printf -- "No files found. %s and TAGS files untouched.\n" "${etags_flist_fname}"  1>&2
+        exit 1
+    else
+        rm -f "${etags_flist_fname}.backup"
+        printf "\
   %s - %s files found and processed.
              Created: %s/TAGS
              Scanned file list stored in: %s/%s\n" "${pgm_name}" "${file_count}" "$(pwd)" "$(pwd)" "${etags_flist_fname}" 1>&2
+    fi
+else
+    printf -- "Appended file list to: %s\nNo TAGS file created\n" "${etags_flist_fname}"
 fi
 
 # ----------------------------------------------------------------------------
