etags-c improvements
- When using fd/fdfind can now search multiple directory trees
- Eliminated code duplication
- Follows symbolic links in directory trees
  - Use appropriate syntax on Linux and macOS (where -f prefix is required)
- Explicitly checks for OS.  Currently Windows is not supported.
- Warn user about possibility of broken symlinks not reported by fd.

diff --git a/bin/etags-c b/bin/etags-c
--- a/bin/etags-c
+++ b/bin/etags-c
@@ -4,7 +4,7 @@
 #  Purpose   : Build Emacs Tags file for C/C++ source code files.
 #  Created   : Monday, November  9 2020.
 #  Author    : Pierre Rouleau <prouleau001@gmail.com>
-#  Time-stamp: <2024-06-06 12:07:25 EDT, updated by Pierre Rouleau>
+#  Time-stamp: <2024-07-22 15:07:35 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 #  Module Description
 #  ------------------
@@ -225,102 +225,110 @@ else
 
     echo "No list of files identified by ETAGS_FILE_LIST."
     echo "- Building the list of source files."
+
     # Find the files, pass their names to etags which creates the TAGS file.
     # To find the files, try to use 'fd' or 'fdfind' if they exist,
     # otherwise use 'find'.  Echo the actual program used to find the files.
     # Search for all possible C and C++ file extensions in the directory tree.
+
+    # - Identify how to search files
     if [ "$ETAGS_USE_FIND" = "1" ]; then
-        echo "- ETAGS_USE_FIND forces the use of find!"
-        echo "-> Using" "$(which find)"
-        find -f "$@" \
-             \(  -name "*.[ch]"      \
-             -or -name "*.[ch].in"   \
-             -or -name "*.[ch]++"    \
-             -or -name "*.[ch]++.in" \
-             -or -name "*.[ch]pp"    \
-             -or -name "*.[ch]pp.in" \
-             -or -name "*.[ch]xx"    \
-             -or -name "*.[ch]xx.in" \
-             -or -name "*.[CH]"      \
-             -or -name "*.[CH].in"   \
-             -or -name "*.cc"        \
-             -or -name "*.cc.in"     \
-             -or -name "*.hh"        \
-             -or -name "*.hh.in"     \
-             -or -name "*.inl"       \
-             -or -name "*.M"         \
-             -or -name "*.pdb"       \
-             \)  -print | tee .etags-c-files.txt | run__etags_c
+        search_with='find'
     else
         if [ -x "$(command -v fdfind)" ]; then
-            echo "-> Using" "$(which fdfind)"
-            echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore"
-            fdfind --type f -e .c      \
-                            -e .c.in   \
-                            -e .h      \
-                            -e .h.in   \
-                            -e .c++    \
-                            -e .c++.in \
-                            -e .h++    \
-                            -e .h++.in \
-                            -e .cpp    \
-                            -e .cpp.in \
-                            -e .hpp    \
-                            -e .hpp.in \
-                            -e .cxx    \
-                            -e .cxx.in \
-                            -e .hxx    \
-                            -e .hxx.in \
-                            -e .C      \
-                            -e .C.in   \
-                            -e .H      \
-                            -e .H.in   \
-                            -e .cc     \
-                            -e .cc.in  \
-                            -e .hh     \
-                            -e .hh.in  \
-                            -e .inl    \
-                            -e .M      \
-                            -e .pdb    \
-                            "$@" | tee .etags-c-files.txt | run__etags_c
+            search_with='fd'
+            fd_pgm=fdfind
         elif [ -x "$(command -v fd)" ]; then
-            echo "-> Using" "$(which fd)"
-            echo "-> ☝️ Ignoring files identified in .gitignore, .ignore or .fdignore"
-            fd --type f -e .c      \
-                        -e .c.in   \
-                        -e .h      \
-                        -e .h.in   \
-                        -e .c++    \
-                        -e .c++.in \
-                        -e .h++    \
-                        -e .h++.in \
-                        -e .cpp    \
-                        -e .cpp.in \
-                        -e .hpp    \
-                        -e .hpp.in \
-                        -e .cxx    \
-                        -e .cxx.in \
-                        -e .hxx    \
-                        -e .hxx.in \
-                        -e .C      \
-                        -e .C.in   \
-                        -e .H      \
-                        -e .H.in   \
-                        -e .cc     \
-                        -e .cc.in  \
-                        -e .hh     \
-                        -e .hh.in  \
-                        -e .inl    \
-                        -e .M      \
-                        -e .pdb    \
-                        "$@" | tee .etags-c-files.txt | run__etags_c
+            search_with='fd'
+            fd_pgm=fd
         else
-            echo "-> Using " "$(which find)"
-            find . -type f "$@" \
-                 \(  -name "*.[ch]" \
-                 \)  -print | tee .etags-c-files.txt | run__etags_c
+            search_with='find'
         fi
     fi
+
+    case $(uname) in
+        Darwin)
+            find_path_option='-f'
+            ;;
+        Linux)
+            find_path_option=
+            ;;
+        *)
+            printf -- "etags-c ** Error Operating System, %s, is not supported!\n" "$(uname)"
+            exit 1
+            ;;
+    esac
+
+    case "$search_with" in
+        find)
+            printf -- "etags-c -- ETAGS_USE_FIND set to 1: forces the use of find!\n"
+            printf --  "       -> Using %s\n" "$(which find)"
+            find -L \
+                 ${find_path_option} "$@" \
+                 \(  -name "*.[ch]"      \
+                 -or -name "*.[ch].in"   \
+                 -or -name "*.[ch]++"    \
+                 -or -name "*.[ch]++.in" \
+                 -or -name "*.[ch]pp"    \
+                 -or -name "*.[ch]pp.in" \
+                 -or -name "*.[ch]xx"    \
+                 -or -name "*.[ch]xx.in" \
+                 -or -name "*.[CH]"      \
+                 -or -name "*.[CH].in"   \
+                 -or -name "*.cc"        \
+                 -or -name "*.cc.in"     \
+                 -or -name "*.hh"        \
+                 -or -name "*.hh.in"     \
+                 -or -name "*.inl"       \
+                 -or -name "*.M"         \
+                 -or -name "*.pdb"       \
+                 \)  -print | tee .etags-c-files.txt | run__etags_c
+            ;;
+
+        fd)
+            printf -- "etags-c -- Using sharkdp/fd fast find.\n"
+            printf -- "        -> Using %s\n" "$(which "${fd_pgm}")"
+            printf -- " -> ☝️  Ignoring files identified in .gitignore, .ignore or .fdignore\n"
+            printf -- " -> ☝️  You may want to run a search with find once to detect broken symlinks\n"
+            ${fd_pgm} --absolute-path \
+                   --follow   \
+                   --type f   \
+                   --type l   \
+                   -e .c      \
+                   -e .c.in   \
+                   -e .h      \
+                   -e .h.in   \
+                   -e .c++    \
+                   -e .c++.in \
+                   -e .h++    \
+                   -e .h++.in \
+                   -e .cpp    \
+                   -e .cpp.in \
+                   -e .hpp    \
+                   -e .hpp.in \
+                   -e .cxx    \
+                   -e .cxx.in \
+                   -e .hxx    \
+                   -e .hxx.in \
+                   -e .C      \
+                   -e .C.in   \
+                   -e .H      \
+                   -e .H.in   \
+                   -e .cc     \
+                   -e .cc.in  \
+                   -e .hh     \
+                   -e .hh.in  \
+                   -e .inl    \
+                   -e .M      \
+                   -e .pdb    \
+                   . "$@" | tee .etags-c-files.txt | run__etags_c
+            ;;
+
+        *)
+            printf -- "etags-c ** Error: cannot identify find program!\n"
+            exit 1
+            ;;
+    esac
 fi
 
 file_count="$(wc -l .etags-c-files.txt | awk '{print $1}')"
