Several small fixes in scripts

diff --git a/bin/is-emacs-daemon-running b/bin/is-emacs-daemon-running
--- a/bin/is-emacs-daemon-running
+++ b/bin/is-emacs-daemon-running
@@ -4,7 +4,7 @@
 # Purpose   : Report if Emacs daemon is currently running or not.
 # Created   : Thursday, August  1 2024.
 # Author    : Pierre Rouleau <prouleau001@gmail.com>
-# Time-stamp: <2026-02-18 18:11:54 EST, updated by Pierre Rouleau>
+# Time-stamp: <2026-03-13 17:08:13 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 # Module Description
 # ------------------
@@ -120,6 +120,11 @@ case "${os_name}" in
                 fi
             fi
         fi
+        ;;
+
+    *)
+        printf -- "*** ERROR: Unsupported OS: %s\n" "${os_name}" 1>&2
+        exit 2
         ;;
 esac
 
