Node uses a relative path to the script

diff --git a/bin/jslint b/bin/jslint
--- a/bin/jslint
+++ b/bin/jslint
@@ -4,7 +4,7 @@
 # Purpose   : Run jslint - Lint Javascript file.
 # Created   : Thursday, October 30 2025.
 # Author    : Pierre Rouleau <prouleau001@gmail.com>
-# Time-stamp: <2025-10-30 14:07:58 EDT, updated by Pierre Rouleau>
+# Time-stamp: <2025-10-30 16:33:48 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 
 # Module Description
@@ -20,6 +20,7 @@
 #
 # - printf, which, ln
 # - node
+# - python : Python 3
 
 # ----------------------------------------------------------------------------
 # Code
@@ -72,7 +73,29 @@ fi
 
 # --
 # proceed
+# Node need to get a RELATIVE path to the $HOME/bin/javascript/jslint.mjs file!
 
-node "$HOME/bin/javascript/jslint.mjs" "$@"
+curdir="$(pwd)"
+file_path="$HOME/bin/javascript/jslint.mjs"
+
+# Use an inline Python script to compute the relative path.
+# Later version of realpath command have an option to do it, but
+# it is not available everywhere.
+#
+rel_jslint=$(python -c "import os.path; print(os.path.relpath('$file_path', '$curdir'))")
+
+# Loop in a POSIX compatible way.
+
+while [ "$#" -gt 0 ]; do
+  fn="$1"
+  shift
+  if [ ! -e "${fn}" ]; then
+    printf -- "***ERROR: does not exist: %s\n" "${fn}"
+    exit 1
+  else
+      # echo "${rel_jslint}" "${fn}"
+      node "${rel_jslint}" "${fn}"
+  fi
+done
 
 # ----------------------------------------------------------------------------
